/**
 * Sequelize Enum Type Definitions
 * All enums from Prisma schema converted to TypeScript enums
 */

export enum UserRole {
  ADMIN = 'ADMIN',
  NURSE = 'NURSE',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  VIEWER = 'VIEWER',
  COUNSELOR = 'COUNSELOR',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  PREFER_NOT_TO_SAY = 'PREFER_NOT_TO_SAY',
}

export enum ContactPriority {
  PRIMARY = 'PRIMARY',
  SECONDARY = 'SECONDARY',
  EMERGENCY_ONLY = 'EMERGENCY_ONLY',
}

export enum HealthRecordType {
  CHECKUP = 'CHECKUP',
  VACCINATION = 'VACCINATION',
  ILLNESS = 'ILLNESS',
  INJURY = 'INJURY',
  SCREENING = 'SCREENING',
  PHYSICAL_EXAM = 'PHYSICAL_EXAM',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  DENTAL = 'DENTAL',
  VISION = 'VISION',
  HEARING = 'HEARING',
  EXAMINATION = 'EXAMINATION',
  ALLERGY_DOCUMENTATION = 'ALLERGY_DOCUMENTATION',
  CHRONIC_CONDITION_REVIEW = 'CHRONIC_CONDITION_REVIEW',
  GROWTH_ASSESSMENT = 'GROWTH_ASSESSMENT',
  VITAL_SIGNS_CHECK = 'VITAL_SIGNS_CHECK',
  EMERGENCY_VISIT = 'EMERGENCY_VISIT',
  FOLLOW_UP = 'FOLLOW_UP',
  CONSULTATION = 'CONSULTATION',
  DIAGNOSTIC_TEST = 'DIAGNOSTIC_TEST',
  PROCEDURE = 'PROCEDURE',
  HOSPITALIZATION = 'HOSPITALIZATION',
  SURGERY = 'SURGERY',
  COUNSELING = 'COUNSELING',
  THERAPY = 'THERAPY',
  NUTRITION = 'NUTRITION',
  MEDICATION_REVIEW = 'MEDICATION_REVIEW',
  IMMUNIZATION = 'IMMUNIZATION',
  LAB_RESULT = 'LAB_RESULT',
  RADIOLOGY = 'RADIOLOGY',
  OTHER = 'OTHER',
}

export enum AllergySeverity {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  LIFE_THREATENING = 'LIFE_THREATENING',
}

export enum AllergyType {
  FOOD = 'FOOD',
  MEDICATION = 'MEDICATION',
  ENVIRONMENTAL = 'ENVIRONMENTAL',
  INSECT = 'INSECT',
  LATEX = 'LATEX',
  ANIMAL = 'ANIMAL',
  CHEMICAL = 'CHEMICAL',
  SEASONAL = 'SEASONAL',
  OTHER = 'OTHER',
}

export enum AppointmentType {
  ROUTINE_CHECKUP = 'ROUTINE_CHECKUP',
  MEDICATION_ADMINISTRATION = 'MEDICATION_ADMINISTRATION',
  INJURY_ASSESSMENT = 'INJURY_ASSESSMENT',
  ILLNESS_EVALUATION = 'ILLNESS_EVALUATION',
  FOLLOW_UP = 'FOLLOW_UP',
  SCREENING = 'SCREENING',
  EMERGENCY = 'EMERGENCY',
}

export enum AppointmentStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
}

export enum IncidentType {
  INJURY = 'INJURY',
  ILLNESS = 'ILLNESS',
  BEHAVIORAL = 'BEHAVIORAL',
  MEDICATION_ERROR = 'MEDICATION_ERROR',
  ALLERGIC_REACTION = 'ALLERGIC_REACTION',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
}

export enum IncidentSeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum MessageType {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
  VOICE = 'VOICE',
}

export enum MessagePriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum DeliveryStatus {
  PENDING = 'PENDING',
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  FAILED = 'FAILED',
  BOUNCED = 'BOUNCED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
  IMPORT = 'IMPORT',
  BACKUP = 'BACKUP',
  RESTORE = 'RESTORE',
}

export enum ComplianceReportType {
  HIPAA = 'HIPAA',
  FERPA = 'FERPA',
  STATE_HEALTH = 'STATE_HEALTH',
  MEDICATION_AUDIT = 'MEDICATION_AUDIT',
  SAFETY_INSPECTION = 'SAFETY_INSPECTION',
  TRAINING_COMPLIANCE = 'TRAINING_COMPLIANCE',
  DATA_PRIVACY = 'DATA_PRIVACY',
  CUSTOM = 'CUSTOM',
}

export enum ComplianceStatus {
  PENDING = 'PENDING',
  COMPLIANT = 'COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum ComplianceCategory {
  PRIVACY = 'PRIVACY',
  SECURITY = 'SECURITY',
  DOCUMENTATION = 'DOCUMENTATION',
  TRAINING = 'TRAINING',
  SAFETY = 'SAFETY',
  MEDICATION = 'MEDICATION',
  HEALTH_RECORDS = 'HEALTH_RECORDS',
  CONSENT = 'CONSENT',
}

export enum ChecklistItemStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  FAILED = 'FAILED',
}

export enum ConsentType {
  MEDICAL_TREATMENT = 'MEDICAL_TREATMENT',
  MEDICATION_ADMINISTRATION = 'MEDICATION_ADMINISTRATION',
  EMERGENCY_CARE = 'EMERGENCY_CARE',
  PHOTO_RELEASE = 'PHOTO_RELEASE',
  DATA_SHARING = 'DATA_SHARING',
  TELEHEALTH = 'TELEHEALTH',
  RESEARCH = 'RESEARCH',
  OTHER = 'OTHER',
}

export enum PolicyCategory {
  HIPAA = 'HIPAA',
  FERPA = 'FERPA',
  MEDICATION = 'MEDICATION',
  EMERGENCY = 'EMERGENCY',
  SAFETY = 'SAFETY',
  DATA_SECURITY = 'DATA_SECURITY',
  OPERATIONAL = 'OPERATIONAL',
  TRAINING = 'TRAINING',
}

export enum PolicyStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum SecurityIncidentType {
  UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
  DATA_BREACH = 'DATA_BREACH',
  FAILED_LOGIN_ATTEMPTS = 'FAILED_LOGIN_ATTEMPTS',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  MALWARE = 'MALWARE',
  PHISHING = 'PHISHING',
  POLICY_VIOLATION = 'POLICY_VIOLATION',
  OTHER = 'OTHER',
}

export enum SecurityIncidentStatus {
  OPEN = 'OPEN',
  INVESTIGATING = 'INVESTIGATING',
  CONTAINED = 'CONTAINED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum IpRestrictionType {
  WHITELIST = 'WHITELIST',
  BLACKLIST = 'BLACKLIST',
}

export enum InventoryTransactionType {
  PURCHASE = 'PURCHASE',
  USAGE = 'USAGE',
  ADJUSTMENT = 'ADJUSTMENT',
  TRANSFER = 'TRANSFER',
  DISPOSAL = 'DISPOSAL',
}

export enum MaintenanceType {
  ROUTINE = 'ROUTINE',
  REPAIR = 'REPAIR',
  CALIBRATION = 'CALIBRATION',
  INSPECTION = 'INSPECTION',
  CLEANING = 'CLEANING',
}

export enum PurchaseOrderStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  ORDERED = 'ORDERED',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}

export enum MessageCategory {
  EMERGENCY = 'EMERGENCY',
  HEALTH_UPDATE = 'HEALTH_UPDATE',
  APPOINTMENT_REMINDER = 'APPOINTMENT_REMINDER',
  MEDICATION_REMINDER = 'MEDICATION_REMINDER',
  GENERAL = 'GENERAL',
  INCIDENT_NOTIFICATION = 'INCIDENT_NOTIFICATION',
  COMPLIANCE = 'COMPLIANCE',
}

export enum RecipientType {
  STUDENT = 'STUDENT',
  EMERGENCY_CONTACT = 'EMERGENCY_CONTACT',
  PARENT = 'PARENT',
  NURSE = 'NURSE',
  ADMIN = 'ADMIN',
}

export enum DocumentCategory {
  MEDICAL_RECORD = 'MEDICAL_RECORD',
  INCIDENT_REPORT = 'INCIDENT_REPORT',
  CONSENT_FORM = 'CONSENT_FORM',
  POLICY = 'POLICY',
  TRAINING = 'TRAINING',
  ADMINISTRATIVE = 'ADMINISTRATIVE',
  STUDENT_FILE = 'STUDENT_FILE',
  INSURANCE = 'INSURANCE',
  OTHER = 'OTHER',
}

export enum DocumentStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  ARCHIVED = 'ARCHIVED',
  EXPIRED = 'EXPIRED',
}

export enum DocumentAccessLevel {
  PUBLIC = 'PUBLIC',
  STAFF_ONLY = 'STAFF_ONLY',
  ADMIN_ONLY = 'ADMIN_ONLY',
  RESTRICTED = 'RESTRICTED',
}

export enum DocumentAction {
  CREATED = 'CREATED',
  VIEWED = 'VIEWED',
  DOWNLOADED = 'DOWNLOADED',
  UPDATED = 'UPDATED',
  DELETED = 'DELETED',
  SHARED = 'SHARED',
  SIGNED = 'SIGNED',
}

export enum IntegrationType {
  SIS = 'SIS',
  EHR = 'EHR',
  PHARMACY = 'PHARMACY',
  LABORATORY = 'LABORATORY',
  INSURANCE = 'INSURANCE',
  PARENT_PORTAL = 'PARENT_PORTAL',
  HEALTH_APP = 'HEALTH_APP',
  GOVERNMENT_REPORTING = 'GOVERNMENT_REPORTING',
}

export enum IntegrationStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  ERROR = 'ERROR',
  TESTING = 'TESTING',
  SYNCING = 'SYNCING',
}

export enum ConfigCategory {
  GENERAL = 'GENERAL',
  SECURITY = 'SECURITY',
  NOTIFICATION = 'NOTIFICATION',
  INTEGRATION = 'INTEGRATION',
  BACKUP = 'BACKUP',
  PERFORMANCE = 'PERFORMANCE',
  HEALTHCARE = 'HEALTHCARE',
  MEDICATION = 'MEDICATION',
  APPOINTMENTS = 'APPOINTMENTS',
  UI = 'UI',
  QUERY = 'QUERY',
  FILE_UPLOAD = 'FILE_UPLOAD',
  RATE_LIMITING = 'RATE_LIMITING',
  SESSION = 'SESSION',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum ConfigValueType {
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  BOOLEAN = 'BOOLEAN',
  JSON = 'JSON',
  ARRAY = 'ARRAY',
  DATE = 'DATE',
  TIME = 'TIME',
  DATETIME = 'DATETIME',
  EMAIL = 'EMAIL',
  URL = 'URL',
  COLOR = 'COLOR',
  ENUM = 'ENUM',
}

export enum ConfigScope {
  SYSTEM = 'SYSTEM',
  DISTRICT = 'DISTRICT',
  SCHOOL = 'SCHOOL',
  USER = 'USER',
}

export enum BackupType {
  AUTOMATIC = 'AUTOMATIC',
  MANUAL = 'MANUAL',
  SCHEDULED = 'SCHEDULED',
}

export enum BackupStatus {
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum MetricType {
  CPU_USAGE = 'CPU_USAGE',
  MEMORY_USAGE = 'MEMORY_USAGE',
  DISK_USAGE = 'DISK_USAGE',
  API_RESPONSE_TIME = 'API_RESPONSE_TIME',
  DATABASE_QUERY_TIME = 'DATABASE_QUERY_TIME',
  ACTIVE_USERS = 'ACTIVE_USERS',
  ERROR_RATE = 'ERROR_RATE',
  REQUEST_COUNT = 'REQUEST_COUNT',
}

export enum LicenseType {
  TRIAL = 'TRIAL',
  BASIC = 'BASIC',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE',
}

export enum LicenseStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED',
}

export enum TrainingCategory {
  HIPAA_COMPLIANCE = 'HIPAA_COMPLIANCE',
  MEDICATION_MANAGEMENT = 'MEDICATION_MANAGEMENT',
  EMERGENCY_PROCEDURES = 'EMERGENCY_PROCEDURES',
  SYSTEM_TRAINING = 'SYSTEM_TRAINING',
  SAFETY_PROTOCOLS = 'SAFETY_PROTOCOLS',
  DATA_SECURITY = 'DATA_SECURITY',
}

export enum ConditionSeverity {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  CRITICAL = 'CRITICAL',
}

export enum ConditionStatus {
  ACTIVE = 'ACTIVE',
  MANAGED = 'MANAGED',
  RESOLVED = 'RESOLVED',
  MONITORING = 'MONITORING',
  INACTIVE = 'INACTIVE',
}

export enum VaccineType {
  COVID_19 = 'COVID_19',
  FLU = 'FLU',
  MEASLES = 'MEASLES',
  MUMPS = 'MUMPS',
  RUBELLA = 'RUBELLA',
  MMR = 'MMR',
  POLIO = 'POLIO',
  HEPATITIS_A = 'HEPATITIS_A',
  HEPATITIS_B = 'HEPATITIS_B',
  VARICELLA = 'VARICELLA',
  TETANUS = 'TETANUS',
  DIPHTHERIA = 'DIPHTHERIA',
  PERTUSSIS = 'PERTUSSIS',
  TDAP = 'TDAP',
  DTaP = 'DTaP',
  HIB = 'HIB',
  PNEUMOCOCCAL = 'PNEUMOCOCCAL',
  ROTAVIRUS = 'ROTAVIRUS',
  MENINGOCOCCAL = 'MENINGOCOCCAL',
  HPV = 'HPV',
  OTHER = 'OTHER',
}

export enum AdministrationSite {
  ARM_LEFT = 'ARM_LEFT',
  ARM_RIGHT = 'ARM_RIGHT',
  THIGH_LEFT = 'THIGH_LEFT',
  THIGH_RIGHT = 'THIGH_RIGHT',
  DELTOID_LEFT = 'DELTOID_LEFT',
  DELTOID_RIGHT = 'DELTOID_RIGHT',
  BUTTOCK_LEFT = 'BUTTOCK_LEFT',
  BUTTOCK_RIGHT = 'BUTTOCK_RIGHT',
  ORAL = 'ORAL',
  NASAL = 'NASAL',
  OTHER = 'OTHER',
}

export enum AdministrationRoute {
  INTRAMUSCULAR = 'INTRAMUSCULAR',
  SUBCUTANEOUS = 'SUBCUTANEOUS',
  INTRADERMAL = 'INTRADERMAL',
  ORAL = 'ORAL',
  INTRANASAL = 'INTRANASAL',
  INTRAVENOUS = 'INTRAVENOUS',
  OTHER = 'OTHER',
}

export enum VaccineComplianceStatus {
  COMPLIANT = 'COMPLIANT',
  OVERDUE = 'OVERDUE',
  PARTIALLY_COMPLIANT = 'PARTIALLY_COMPLIANT',
  EXEMPT = 'EXEMPT',
  NON_COMPLIANT = 'NON_COMPLIANT',
}

export enum ScreeningType {
  VISION = 'VISION',
  HEARING = 'HEARING',
  SCOLIOSIS = 'SCOLIOSIS',
  DENTAL = 'DENTAL',
  BMI = 'BMI',
  BLOOD_PRESSURE = 'BLOOD_PRESSURE',
  DEVELOPMENTAL = 'DEVELOPMENTAL',
  SPEECH = 'SPEECH',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  TUBERCULOSIS = 'TUBERCULOSIS',
  LEAD = 'LEAD',
  ANEMIA = 'ANEMIA',
  OTHER = 'OTHER',
}

export enum ScreeningOutcome {
  PASS = 'PASS',
  REFER = 'REFER',
  FAIL = 'FAIL',
  INCONCLUSIVE = 'INCONCLUSIVE',
  INCOMPLETE = 'INCOMPLETE',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  SCHEDULED = 'SCHEDULED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  OVERDUE = 'OVERDUE',
  NOT_NEEDED = 'NOT_NEEDED',
}

export enum ConsciousnessLevel {
  ALERT = 'ALERT',
  VERBAL = 'VERBAL',
  PAIN = 'PAIN',
  UNRESPONSIVE = 'UNRESPONSIVE',
  DROWSY = 'DROWSY',
  CONFUSED = 'CONFUSED',
  LETHARGIC = 'LETHARGIC',
}

export enum WaitlistPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum WaitlistStatus {
  WAITING = 'WAITING',
  NOTIFIED = 'NOTIFIED',
  SCHEDULED = 'SCHEDULED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum ReminderStatus {
  SCHEDULED = 'SCHEDULED',
  SENT = 'SENT',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum WitnessType {
  STUDENT = 'STUDENT',
  STAFF = 'STAFF',
  PARENT = 'PARENT',
  OTHER = 'OTHER',
}

export enum ActionPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum ActionStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum InsuranceClaimStatus {
  NOT_FILED = 'NOT_FILED',
  FILED = 'FILED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  DENIED = 'DENIED',
  CLOSED = 'CLOSED',
}
