/**
 * Comprehensive Medication Database for School Health Services
 * Organized by category with NDC codes and proper clinical information
 */

export const medicationsData = [
  // ========== RESPIRATORY MEDICATIONS ==========
  {
    name: 'Albuterol Inhaler',
    genericName: 'Albuterol Sulfate',
    dosageForm: 'Inhaler',
    strength: '90 mcg/dose',
    manufacturer: 'ProAir',
    ndc: '66993-0520-68',
    isControlled: false,
  },
  {
    name: 'Levalbuterol Inhaler',
    genericName: 'Levalbuterol',
    dosageForm: 'Inhaler',
    strength: '45 mcg/dose',
    manufacturer: 'Xopenex',
    ndc: '63402-0301-05',
    isControlled: false,
  },
  {
    name: 'Budesonide Inhaler',
    genericName: 'Budesonide',
    dosageForm: 'Inhaler',
    strength: '80 mcg/dose',
    manufacturer: 'Pulmicort',
    ndc: '00186-0382-03',
    isControlled: false,
  },
  {
    name: 'Fluticasone Inhaler',
    genericName: 'Fluticasone Propionate',
    dosageForm: 'Inhaler',
    strength: '44 mcg/dose',
    manufacturer: 'Flovent',
    ndc: '00173-0452-00',
    isControlled: false,
  },

  // ========== EMERGENCY MEDICATIONS ==========
  {
    name: 'EpiPen',
    genericName: 'Epinephrine',
    dosageForm: 'Auto-injector',
    strength: '0.3 mg',
    manufacturer: 'Mylan',
    ndc: '49502-0500-02',
    isControlled: false,
  },
  {
    name: 'EpiPen Jr',
    genericName: 'Epinephrine',
    dosageForm: 'Auto-injector',
    strength: '0.15 mg',
    manufacturer: 'Mylan',
    ndc: '49502-0501-02',
    isControlled: false,
  },
  {
    name: 'Glucagon Emergency Kit',
    genericName: 'Glucagon',
    dosageForm: 'Injection',
    strength: '1 mg',
    manufacturer: 'Lilly',
    ndc: '00002-8801-01',
    isControlled: false,
  },

  // ========== PAIN/FEVER RELIEVERS ==========
  {
    name: 'Tylenol',
    genericName: 'Acetaminophen',
    dosageForm: 'Tablet',
    strength: '325 mg',
    manufacturer: 'Johnson & Johnson',
    ndc: '50580-0506-01',
    isControlled: false,
  },
  {
    name: 'Tylenol Extra Strength',
    genericName: 'Acetaminophen',
    dosageForm: 'Tablet',
    strength: '500 mg',
    manufacturer: 'Johnson & Johnson',
    ndc: '50580-0449-01',
    isControlled: false,
  },
  {
    name: "Children's Tylenol",
    genericName: 'Acetaminophen',
    dosageForm: 'Liquid',
    strength: '160 mg/5mL',
    manufacturer: 'Johnson & Johnson',
    ndc: '50580-0206-02',
    isControlled: false,
  },
  {
    name: 'Ibuprofen',
    genericName: 'Ibuprofen',
    dosageForm: 'Tablet',
    strength: '200 mg',
    manufacturer: 'Advil',
    ndc: '00573-0165-70',
    isControlled: false,
  },
  {
    name: "Children's Ibuprofen",
    genericName: 'Ibuprofen',
    dosageForm: 'Liquid',
    strength: '100 mg/5mL',
    manufacturer: 'Motrin',
    ndc: '50580-0451-04',
    isControlled: false,
  },

  // ========== ADHD MEDICATIONS (Controlled) ==========
  {
    name: 'Methylphenidate',
    genericName: 'Methylphenidate HCl',
    dosageForm: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Ritalin',
    ndc: '00078-0347-05',
    isControlled: true,
  },
  {
    name: 'Methylphenidate ER',
    genericName: 'Methylphenidate HCl',
    dosageForm: 'Extended Release',
    strength: '18 mg',
    manufacturer: 'Concerta',
    ndc: '00078-0379-05',
    isControlled: true,
  },
  {
    name: 'Adderall',
    genericName: 'Amphetamine/Dextroamphetamine',
    dosageForm: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Teva',
    ndc: '00555-0768-02',
    isControlled: true,
  },
  {
    name: 'Adderall XR',
    genericName: 'Amphetamine/Dextroamphetamine',
    dosageForm: 'Extended Release Capsule',
    strength: '10 mg',
    manufacturer: 'Shire',
    ndc: '54092-0381-30',
    isControlled: true,
  },
  {
    name: 'Vyvanse',
    genericName: 'Lisdexamfetamine',
    dosageForm: 'Capsule',
    strength: '30 mg',
    manufacturer: 'Shire',
    ndc: '59417-0102-30',
    isControlled: true,
  },

  // ========== ANTIHISTAMINES/ALLERGY MEDICATIONS ==========
  {
    name: 'Benadryl',
    genericName: 'Diphenhydramine',
    dosageForm: 'Capsule',
    strength: '25 mg',
    manufacturer: 'Johnson & Johnson',
    ndc: '50580-0170-01',
    isControlled: false,
  },
  {
    name: "Children's Benadryl",
    genericName: 'Diphenhydramine',
    dosageForm: 'Liquid',
    strength: '12.5 mg/5mL',
    manufacturer: 'Johnson & Johnson',
    ndc: '50580-0225-04',
    isControlled: false,
  },
  {
    name: 'Zyrtec',
    genericName: 'Cetirizine',
    dosageForm: 'Tablet',
    strength: '10 mg',
    manufacturer: 'UCB',
    ndc: '50580-0506-70',
    isControlled: false,
  },
  {
    name: 'Claritin',
    genericName: 'Loratadine',
    dosageForm: 'Tablet',
    strength: '10 mg',
    manufacturer: 'Bayer',
    ndc: '11523-7224-1',
    isControlled: false,
  },

  // ========== DIABETES MEDICATIONS ==========
  {
    name: 'Insulin Humalog',
    genericName: 'Insulin Lispro',
    dosageForm: 'Injection',
    strength: '100 units/mL',
    manufacturer: 'Lilly',
    ndc: '00002-7510-01',
    isControlled: false,
  },
  {
    name: 'Insulin NovoLog',
    genericName: 'Insulin Aspart',
    dosageForm: 'Injection',
    strength: '100 units/mL',
    manufacturer: 'Novo Nordisk',
    ndc: '00169-7501-11',
    isControlled: false,
  },
  {
    name: 'Insulin Lantus',
    genericName: 'Insulin Glargine',
    dosageForm: 'Injection',
    strength: '100 units/mL',
    manufacturer: 'Sanofi',
    ndc: '00088-2220-33',
    isControlled: false,
  },
  {
    name: 'Glucose Tablets',
    genericName: 'Dextrose',
    dosageForm: 'Chewable Tablet',
    strength: '4 g',
    manufacturer: 'BD',
    ndc: '08290-3361-01',
    isControlled: false,
  },

  // ========== ANTIBIOTICS ==========
  {
    name: 'Amoxicillin',
    genericName: 'Amoxicillin',
    dosageForm: 'Capsule',
    strength: '500 mg',
    manufacturer: 'Generic',
    ndc: '00093-4155-01',
    isControlled: false,
  },
  {
    name: 'Amoxicillin Suspension',
    genericName: 'Amoxicillin',
    dosageForm: 'Liquid',
    strength: '250 mg/5mL',
    manufacturer: 'Generic',
    ndc: '00093-4155-73',
    isControlled: false,
  },
  {
    name: 'Azithromycin',
    genericName: 'Azithromycin',
    dosageForm: 'Tablet',
    strength: '250 mg',
    manufacturer: 'Generic',
    ndc: '00093-7146-56',
    isControlled: false,
  },
  {
    name: 'Cephalexin',
    genericName: 'Cephalexin',
    dosageForm: 'Capsule',
    strength: '500 mg',
    manufacturer: 'Generic',
    ndc: '00093-3147-01',
    isControlled: false,
  },

  // ========== SEIZURE MEDICATIONS ==========
  {
    name: 'Keppra',
    genericName: 'Levetiracetam',
    dosageForm: 'Tablet',
    strength: '500 mg',
    manufacturer: 'UCB',
    ndc: '50474-0550-50',
    isControlled: false,
  },
  {
    name: 'Depakote',
    genericName: 'Divalproex Sodium',
    dosageForm: 'Tablet',
    strength: '250 mg',
    manufacturer: 'AbbVie',
    ndc: '00074-6211-13',
    isControlled: false,
  },
  {
    name: 'Diastat',
    genericName: 'Diazepam',
    dosageForm: 'Rectal Gel',
    strength: '10 mg',
    manufacturer: 'Bausch Health',
    ndc: '67386-0511-55',
    isControlled: true,
  },

  // ========== GASTROINTESTINAL ==========
  {
    name: 'Pepto-Bismol',
    genericName: 'Bismuth Subsalicylate',
    dosageForm: 'Liquid',
    strength: '262 mg/15mL',
    manufacturer: 'P&G',
    ndc: '37000-0496-15',
    isControlled: false,
  },
  {
    name: 'Mylanta',
    genericName: 'Aluminum/Magnesium Hydroxide',
    dosageForm: 'Liquid',
    strength: '200-200 mg/5mL',
    manufacturer: 'McNeil',
    ndc: '16837-0870-26',
    isControlled: false,
  },

  // ========== TOPICAL/FIRST AID ==========
  {
    name: 'Hydrocortisone Cream',
    genericName: 'Hydrocortisone',
    dosageForm: 'Cream',
    strength: '1%',
    manufacturer: 'Generic',
    ndc: '00168-0011-31',
    isControlled: false,
  },
  {
    name: 'Neosporin',
    genericName: 'Bacitracin/Neomycin/Polymyxin',
    dosageForm: 'Ointment',
    strength: 'Triple Antibiotic',
    manufacturer: 'Johnson & Johnson',
    ndc: '00067-0989-30',
    isControlled: false,
  },
  {
    name: 'Calamine Lotion',
    genericName: 'Calamine',
    dosageForm: 'Lotion',
    strength: '8%',
    manufacturer: 'Generic',
    ndc: '00574-7034-06',
    isControlled: false,
  },
];
