"use strict";
var __esDecorate = (this && this.__esDecorate) || function (ctor, descriptorIn, decorators, contextIn, initializers, extraInitializers) {
    function accept(f) { if (f !== void 0 && typeof f !== "function") throw new TypeError("Function expected"); return f; }
    var kind = contextIn.kind, key = kind === "getter" ? "get" : kind === "setter" ? "set" : "value";
    var target = !descriptorIn && ctor ? contextIn["static"] ? ctor : ctor.prototype : null;
    var descriptor = descriptorIn || (target ? Object.getOwnPropertyDescriptor(target, contextIn.name) : {});
    var _, done = false;
    for (var i = decorators.length - 1; i >= 0; i--) {
        var context = {};
        for (var p in contextIn) context[p] = p === "access" ? {} : contextIn[p];
        for (var p in contextIn.access) context.access[p] = contextIn.access[p];
        context.addInitializer = function (f) { if (done) throw new TypeError("Cannot add initializers after decoration has completed"); extraInitializers.push(accept(f || null)); };
        var result = (0, decorators[i])(kind === "accessor" ? { get: descriptor.get, set: descriptor.set } : descriptor[key], context);
        if (kind === "accessor") {
            if (result === void 0) continue;
            if (result === null || typeof result !== "object") throw new TypeError("Object expected");
            if (_ = accept(result.get)) descriptor.get = _;
            if (_ = accept(result.set)) descriptor.set = _;
            if (_ = accept(result.init)) initializers.unshift(_);
        }
        else if (_ = accept(result)) {
            if (kind === "field") initializers.unshift(_);
            else descriptor[key] = _;
        }
    }
    if (target) Object.defineProperty(target, contextIn.name, descriptor);
    done = true;
};
var __runInitializers = (this && this.__runInitializers) || function (thisArg, initializers, value) {
    var useValue = arguments.length > 2;
    for (var i = 0; i < initializers.length; i++) {
        value = useValue ? initializers[i].call(thisArg, value) : initializers[i].call(thisArg);
    }
    return useValue ? value : void 0;
};
var __setFunctionName = (this && this.__setFunctionName) || function (f, name, prefix) {
    if (typeof name === "symbol") name = name.description ? "[".concat(name.description, "]") : "";
    return Object.defineProperty(f, "name", { configurable: true, value: prefix ? "".concat(prefix, " ", name) : name });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ConstructionContract = void 0;
const sequelize_typescript_1 = require("sequelize-typescript");
const contract_types_1 = require("../types/contract.types");
const payment_application_model_1 = require("./payment-application.model");
const contract_amendment_model_1 = require("./contract-amendment.model");
const contract_milestone_model_1 = require("./contract-milestone.model");
let ConstructionContract = (() => {
    let _classDecorators = [(0, sequelize_typescript_1.Table)({
            tableName: 'construction_contracts',
            timestamps: true,
        })];
    let _classDescriptor;
    let _classExtraInitializers = [];
    let _classThis;
    let _classSuper = sequelize_typescript_1.Model;
    let _id_decorators;
    let _id_initializers = [];
    let _id_extraInitializers = [];
    let _contractNumber_decorators;
    let _contractNumber_initializers = [];
    let _contractNumber_extraInitializers = [];
    let _projectId_decorators;
    let _projectId_initializers = [];
    let _projectId_extraInitializers = [];
    let _projectName_decorators;
    let _projectName_initializers = [];
    let _projectName_extraInitializers = [];
    let _contractorId_decorators;
    let _contractorId_initializers = [];
    let _contractorId_extraInitializers = [];
    let _contractorName_decorators;
    let _contractorName_initializers = [];
    let _contractorName_extraInitializers = [];
    let _contractType_decorators;
    let _contractType_initializers = [];
    let _contractType_extraInitializers = [];
    let _status_decorators;
    let _status_initializers = [];
    let _status_extraInitializers = [];
    let _contractAmount_decorators;
    let _contractAmount_initializers = [];
    let _contractAmount_extraInitializers = [];
    let _originalAmount_decorators;
    let _originalAmount_initializers = [];
    let _originalAmount_extraInitializers = [];
    let _currentAmount_decorators;
    let _currentAmount_initializers = [];
    let _currentAmount_extraInitializers = [];
    let _totalPaid_decorators;
    let _totalPaid_initializers = [];
    let _totalPaid_extraInitializers = [];
    let _retainagePercentage_decorators;
    let _retainagePercentage_initializers = [];
    let _retainagePercentage_extraInitializers = [];
    let _retainageAmount_decorators;
    let _retainageAmount_initializers = [];
    let _retainageAmount_extraInitializers = [];
    let _startDate_decorators;
    let _startDate_initializers = [];
    let _startDate_extraInitializers = [];
    let _completionDate_decorators;
    let _completionDate_initializers = [];
    let _completionDate_extraInitializers = [];
    let _actualStartDate_decorators;
    let _actualStartDate_initializers = [];
    let _actualStartDate_extraInitializers = [];
    let _actualCompletionDate_decorators;
    let _actualCompletionDate_initializers = [];
    let _actualCompletionDate_extraInitializers = [];
    let _substantialCompletionDate_decorators;
    let _substantialCompletionDate_initializers = [];
    let _substantialCompletionDate_extraInitializers = [];
    let _noticeToProceedDate_decorators;
    let _noticeToProceedDate_initializers = [];
    let _noticeToProceedDate_extraInitializers = [];
    let _contractDuration_decorators;
    let _contractDuration_initializers = [];
    let _contractDuration_extraInitializers = [];
    let _daysExtended_decorators;
    let _daysExtended_initializers = [];
    let _daysExtended_extraInitializers = [];
    let _description_decorators;
    let _description_initializers = [];
    let _description_extraInitializers = [];
    let _scopeOfWork_decorators;
    let _scopeOfWork_initializers = [];
    let _scopeOfWork_extraInitializers = [];
    let _performanceBondRequired_decorators;
    let _performanceBondRequired_initializers = [];
    let _performanceBondRequired_extraInitializers = [];
    let _paymentBondRequired_decorators;
    let _paymentBondRequired_initializers = [];
    let _paymentBondRequired_extraInitializers = [];
    let _insuranceRequired_decorators;
    let _insuranceRequired_initializers = [];
    let _insuranceRequired_extraInitializers = [];
    let _prevailingWageRequired_decorators;
    let _prevailingWageRequired_initializers = [];
    let _prevailingWageRequired_extraInitializers = [];
    let _liquidatedDamagesRate_decorators;
    let _liquidatedDamagesRate_initializers = [];
    let _liquidatedDamagesRate_extraInitializers = [];
    let _warrantyPeriod_decorators;
    let _warrantyPeriod_initializers = [];
    let _warrantyPeriod_extraInitializers = [];
    let _metadata_decorators;
    let _metadata_initializers = [];
    let _metadata_extraInitializers = [];
    let _createdBy_decorators;
    let _createdBy_initializers = [];
    let _createdBy_extraInitializers = [];
    let _updatedBy_decorators;
    let _updatedBy_initializers = [];
    let _updatedBy_extraInitializers = [];
    let _paymentApplications_decorators;
    let _paymentApplications_initializers = [];
    let _paymentApplications_extraInitializers = [];
    let _amendments_decorators;
    let _amendments_initializers = [];
    let _amendments_extraInitializers = [];
    let _milestones_decorators;
    let _milestones_initializers = [];
    let _milestones_extraInitializers = [];
    var ConstructionContract = _classThis = class extends _classSuper {
        constructor() {
            super(...arguments);
            this.id = __runInitializers(this, _id_initializers, void 0);
            this.contractNumber = (__runInitializers(this, _id_extraInitializers), __runInitializers(this, _contractNumber_initializers, void 0));
            this.projectId = (__runInitializers(this, _contractNumber_extraInitializers), __runInitializers(this, _projectId_initializers, void 0));
            this.projectName = (__runInitializers(this, _projectId_extraInitializers), __runInitializers(this, _projectName_initializers, void 0));
            this.contractorId = (__runInitializers(this, _projectName_extraInitializers), __runInitializers(this, _contractorId_initializers, void 0));
            this.contractorName = (__runInitializers(this, _contractorId_extraInitializers), __runInitializers(this, _contractorName_initializers, void 0));
            this.contractType = (__runInitializers(this, _contractorName_extraInitializers), __runInitializers(this, _contractType_initializers, void 0));
            this.status = (__runInitializers(this, _contractType_extraInitializers), __runInitializers(this, _status_initializers, void 0));
            this.contractAmount = (__runInitializers(this, _status_extraInitializers), __runInitializers(this, _contractAmount_initializers, void 0));
            this.originalAmount = (__runInitializers(this, _contractAmount_extraInitializers), __runInitializers(this, _originalAmount_initializers, void 0));
            this.currentAmount = (__runInitializers(this, _originalAmount_extraInitializers), __runInitializers(this, _currentAmount_initializers, void 0));
            this.totalPaid = (__runInitializers(this, _currentAmount_extraInitializers), __runInitializers(this, _totalPaid_initializers, void 0));
            this.retainagePercentage = (__runInitializers(this, _totalPaid_extraInitializers), __runInitializers(this, _retainagePercentage_initializers, void 0));
            this.retainageAmount = (__runInitializers(this, _retainagePercentage_extraInitializers), __runInitializers(this, _retainageAmount_initializers, void 0));
            this.startDate = (__runInitializers(this, _retainageAmount_extraInitializers), __runInitializers(this, _startDate_initializers, void 0));
            this.completionDate = (__runInitializers(this, _startDate_extraInitializers), __runInitializers(this, _completionDate_initializers, void 0));
            this.actualStartDate = (__runInitializers(this, _completionDate_extraInitializers), __runInitializers(this, _actualStartDate_initializers, void 0));
            this.actualCompletionDate = (__runInitializers(this, _actualStartDate_extraInitializers), __runInitializers(this, _actualCompletionDate_initializers, void 0));
            this.substantialCompletionDate = (__runInitializers(this, _actualCompletionDate_extraInitializers), __runInitializers(this, _substantialCompletionDate_initializers, void 0));
            this.noticeToProceedDate = (__runInitializers(this, _substantialCompletionDate_extraInitializers), __runInitializers(this, _noticeToProceedDate_initializers, void 0));
            this.contractDuration = (__runInitializers(this, _noticeToProceedDate_extraInitializers), __runInitializers(this, _contractDuration_initializers, void 0)); // in days
            this.daysExtended = (__runInitializers(this, _contractDuration_extraInitializers), __runInitializers(this, _daysExtended_initializers, void 0));
            this.description = (__runInitializers(this, _daysExtended_extraInitializers), __runInitializers(this, _description_initializers, void 0));
            this.scopeOfWork = (__runInitializers(this, _description_extraInitializers), __runInitializers(this, _scopeOfWork_initializers, void 0));
            this.performanceBondRequired = (__runInitializers(this, _scopeOfWork_extraInitializers), __runInitializers(this, _performanceBondRequired_initializers, void 0));
            this.paymentBondRequired = (__runInitializers(this, _performanceBondRequired_extraInitializers), __runInitializers(this, _paymentBondRequired_initializers, void 0));
            this.insuranceRequired = (__runInitializers(this, _paymentBondRequired_extraInitializers), __runInitializers(this, _insuranceRequired_initializers, void 0));
            this.prevailingWageRequired = (__runInitializers(this, _insuranceRequired_extraInitializers), __runInitializers(this, _prevailingWageRequired_initializers, void 0));
            this.liquidatedDamagesRate = (__runInitializers(this, _prevailingWageRequired_extraInitializers), __runInitializers(this, _liquidatedDamagesRate_initializers, void 0));
            this.warrantyPeriod = (__runInitializers(this, _liquidatedDamagesRate_extraInitializers), __runInitializers(this, _warrantyPeriod_initializers, void 0)); // in months
            this.metadata = (__runInitializers(this, _warrantyPeriod_extraInitializers), __runInitializers(this, _metadata_initializers, void 0));
            this.createdBy = (__runInitializers(this, _metadata_extraInitializers), __runInitializers(this, _createdBy_initializers, void 0));
            this.updatedBy = (__runInitializers(this, _createdBy_extraInitializers), __runInitializers(this, _updatedBy_initializers, void 0));
            this.paymentApplications = (__runInitializers(this, _updatedBy_extraInitializers), __runInitializers(this, _paymentApplications_initializers, void 0));
            this.amendments = (__runInitializers(this, _paymentApplications_extraInitializers), __runInitializers(this, _amendments_initializers, void 0));
            this.milestones = (__runInitializers(this, _amendments_extraInitializers), __runInitializers(this, _milestones_initializers, void 0));
            __runInitializers(this, _milestones_extraInitializers);
        }
    };
    __setFunctionName(_classThis, "ConstructionContract");
    (() => {
        const _metadata = typeof Symbol === "function" && Symbol.metadata ? Object.create(_classSuper[Symbol.metadata] ?? null) : void 0;
        _id_decorators = [sequelize_typescript_1.PrimaryKey, (0, sequelize_typescript_1.Default)(sequelize_typescript_1.DataType.UUIDV4), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.UUID)];
        _contractNumber_decorators = [(0, sequelize_typescript_1.AllowNull)(false), Unique, (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.STRING(50))];
        _projectId_decorators = [(0, sequelize_typescript_1.AllowNull)(false), sequelize_typescript_1.Index, (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.UUID)];
        _projectName_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.STRING(255))];
        _contractorId_decorators = [(0, sequelize_typescript_1.AllowNull)(false), sequelize_typescript_1.Index, (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.UUID)];
        _contractorName_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.STRING(255))];
        _contractType_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)({
                type: sequelize_typescript_1.DataType.ENUM(...Object.values(contract_types_1.ContractType)),
            })];
        _status_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(contract_types_1.ContractStatus.DRAFT), (0, sequelize_typescript_1.Column)({
                type: sequelize_typescript_1.DataType.ENUM(...Object.values(contract_types_1.ContractStatus)),
            })];
        _contractAmount_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(19, 2))];
        _originalAmount_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(19, 2))];
        _currentAmount_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(19, 2))];
        _totalPaid_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(0), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(19, 2))];
        _retainagePercentage_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(5, 2))];
        _retainageAmount_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(0), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(19, 2))];
        _startDate_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DATE)];
        _completionDate_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DATE)];
        _actualStartDate_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DATE)];
        _actualCompletionDate_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DATE)];
        _substantialCompletionDate_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DATE)];
        _noticeToProceedDate_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DATE)];
        _contractDuration_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.INTEGER)];
        _daysExtended_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(0), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.INTEGER)];
        _description_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _scopeOfWork_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.TEXT)];
        _performanceBondRequired_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.BOOLEAN)];
        _paymentBondRequired_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.BOOLEAN)];
        _insuranceRequired_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.BOOLEAN)];
        _prevailingWageRequired_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.BOOLEAN)];
        _liquidatedDamagesRate_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.DECIMAL(19, 2))];
        _warrantyPeriod_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.INTEGER)];
        _metadata_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Default)({}), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.JSON)];
        _createdBy_decorators = [(0, sequelize_typescript_1.AllowNull)(false), (0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.STRING(100))];
        _updatedBy_decorators = [(0, sequelize_typescript_1.Column)(sequelize_typescript_1.DataType.STRING(100))];
        _paymentApplications_decorators = [(0, sequelize_typescript_1.HasMany)(() => payment_application_model_1.PaymentApplication)];
        _amendments_decorators = [(0, sequelize_typescript_1.HasMany)(() => contract_amendment_model_1.ContractAmendment)];
        _milestones_decorators = [(0, sequelize_typescript_1.HasMany)(() => contract_milestone_model_1.ContractMilestone)];
        __esDecorate(null, null, _id_decorators, { kind: "field", name: "id", static: false, private: false, access: { has: obj => "id" in obj, get: obj => obj.id, set: (obj, value) => { obj.id = value; } }, metadata: _metadata }, _id_initializers, _id_extraInitializers);
        __esDecorate(null, null, _contractNumber_decorators, { kind: "field", name: "contractNumber", static: false, private: false, access: { has: obj => "contractNumber" in obj, get: obj => obj.contractNumber, set: (obj, value) => { obj.contractNumber = value; } }, metadata: _metadata }, _contractNumber_initializers, _contractNumber_extraInitializers);
        __esDecorate(null, null, _projectId_decorators, { kind: "field", name: "projectId", static: false, private: false, access: { has: obj => "projectId" in obj, get: obj => obj.projectId, set: (obj, value) => { obj.projectId = value; } }, metadata: _metadata }, _projectId_initializers, _projectId_extraInitializers);
        __esDecorate(null, null, _projectName_decorators, { kind: "field", name: "projectName", static: false, private: false, access: { has: obj => "projectName" in obj, get: obj => obj.projectName, set: (obj, value) => { obj.projectName = value; } }, metadata: _metadata }, _projectName_initializers, _projectName_extraInitializers);
        __esDecorate(null, null, _contractorId_decorators, { kind: "field", name: "contractorId", static: false, private: false, access: { has: obj => "contractorId" in obj, get: obj => obj.contractorId, set: (obj, value) => { obj.contractorId = value; } }, metadata: _metadata }, _contractorId_initializers, _contractorId_extraInitializers);
        __esDecorate(null, null, _contractorName_decorators, { kind: "field", name: "contractorName", static: false, private: false, access: { has: obj => "contractorName" in obj, get: obj => obj.contractorName, set: (obj, value) => { obj.contractorName = value; } }, metadata: _metadata }, _contractorName_initializers, _contractorName_extraInitializers);
        __esDecorate(null, null, _contractType_decorators, { kind: "field", name: "contractType", static: false, private: false, access: { has: obj => "contractType" in obj, get: obj => obj.contractType, set: (obj, value) => { obj.contractType = value; } }, metadata: _metadata }, _contractType_initializers, _contractType_extraInitializers);
        __esDecorate(null, null, _status_decorators, { kind: "field", name: "status", static: false, private: false, access: { has: obj => "status" in obj, get: obj => obj.status, set: (obj, value) => { obj.status = value; } }, metadata: _metadata }, _status_initializers, _status_extraInitializers);
        __esDecorate(null, null, _contractAmount_decorators, { kind: "field", name: "contractAmount", static: false, private: false, access: { has: obj => "contractAmount" in obj, get: obj => obj.contractAmount, set: (obj, value) => { obj.contractAmount = value; } }, metadata: _metadata }, _contractAmount_initializers, _contractAmount_extraInitializers);
        __esDecorate(null, null, _originalAmount_decorators, { kind: "field", name: "originalAmount", static: false, private: false, access: { has: obj => "originalAmount" in obj, get: obj => obj.originalAmount, set: (obj, value) => { obj.originalAmount = value; } }, metadata: _metadata }, _originalAmount_initializers, _originalAmount_extraInitializers);
        __esDecorate(null, null, _currentAmount_decorators, { kind: "field", name: "currentAmount", static: false, private: false, access: { has: obj => "currentAmount" in obj, get: obj => obj.currentAmount, set: (obj, value) => { obj.currentAmount = value; } }, metadata: _metadata }, _currentAmount_initializers, _currentAmount_extraInitializers);
        __esDecorate(null, null, _totalPaid_decorators, { kind: "field", name: "totalPaid", static: false, private: false, access: { has: obj => "totalPaid" in obj, get: obj => obj.totalPaid, set: (obj, value) => { obj.totalPaid = value; } }, metadata: _metadata }, _totalPaid_initializers, _totalPaid_extraInitializers);
        __esDecorate(null, null, _retainagePercentage_decorators, { kind: "field", name: "retainagePercentage", static: false, private: false, access: { has: obj => "retainagePercentage" in obj, get: obj => obj.retainagePercentage, set: (obj, value) => { obj.retainagePercentage = value; } }, metadata: _metadata }, _retainagePercentage_initializers, _retainagePercentage_extraInitializers);
        __esDecorate(null, null, _retainageAmount_decorators, { kind: "field", name: "retainageAmount", static: false, private: false, access: { has: obj => "retainageAmount" in obj, get: obj => obj.retainageAmount, set: (obj, value) => { obj.retainageAmount = value; } }, metadata: _metadata }, _retainageAmount_initializers, _retainageAmount_extraInitializers);
        __esDecorate(null, null, _startDate_decorators, { kind: "field", name: "startDate", static: false, private: false, access: { has: obj => "startDate" in obj, get: obj => obj.startDate, set: (obj, value) => { obj.startDate = value; } }, metadata: _metadata }, _startDate_initializers, _startDate_extraInitializers);
        __esDecorate(null, null, _completionDate_decorators, { kind: "field", name: "completionDate", static: false, private: false, access: { has: obj => "completionDate" in obj, get: obj => obj.completionDate, set: (obj, value) => { obj.completionDate = value; } }, metadata: _metadata }, _completionDate_initializers, _completionDate_extraInitializers);
        __esDecorate(null, null, _actualStartDate_decorators, { kind: "field", name: "actualStartDate", static: false, private: false, access: { has: obj => "actualStartDate" in obj, get: obj => obj.actualStartDate, set: (obj, value) => { obj.actualStartDate = value; } }, metadata: _metadata }, _actualStartDate_initializers, _actualStartDate_extraInitializers);
        __esDecorate(null, null, _actualCompletionDate_decorators, { kind: "field", name: "actualCompletionDate", static: false, private: false, access: { has: obj => "actualCompletionDate" in obj, get: obj => obj.actualCompletionDate, set: (obj, value) => { obj.actualCompletionDate = value; } }, metadata: _metadata }, _actualCompletionDate_initializers, _actualCompletionDate_extraInitializers);
        __esDecorate(null, null, _substantialCompletionDate_decorators, { kind: "field", name: "substantialCompletionDate", static: false, private: false, access: { has: obj => "substantialCompletionDate" in obj, get: obj => obj.substantialCompletionDate, set: (obj, value) => { obj.substantialCompletionDate = value; } }, metadata: _metadata }, _substantialCompletionDate_initializers, _substantialCompletionDate_extraInitializers);
        __esDecorate(null, null, _noticeToProceedDate_decorators, { kind: "field", name: "noticeToProceedDate", static: false, private: false, access: { has: obj => "noticeToProceedDate" in obj, get: obj => obj.noticeToProceedDate, set: (obj, value) => { obj.noticeToProceedDate = value; } }, metadata: _metadata }, _noticeToProceedDate_initializers, _noticeToProceedDate_extraInitializers);
        __esDecorate(null, null, _contractDuration_decorators, { kind: "field", name: "contractDuration", static: false, private: false, access: { has: obj => "contractDuration" in obj, get: obj => obj.contractDuration, set: (obj, value) => { obj.contractDuration = value; } }, metadata: _metadata }, _contractDuration_initializers, _contractDuration_extraInitializers);
        __esDecorate(null, null, _daysExtended_decorators, { kind: "field", name: "daysExtended", static: false, private: false, access: { has: obj => "daysExtended" in obj, get: obj => obj.daysExtended, set: (obj, value) => { obj.daysExtended = value; } }, metadata: _metadata }, _daysExtended_initializers, _daysExtended_extraInitializers);
        __esDecorate(null, null, _description_decorators, { kind: "field", name: "description", static: false, private: false, access: { has: obj => "description" in obj, get: obj => obj.description, set: (obj, value) => { obj.description = value; } }, metadata: _metadata }, _description_initializers, _description_extraInitializers);
        __esDecorate(null, null, _scopeOfWork_decorators, { kind: "field", name: "scopeOfWork", static: false, private: false, access: { has: obj => "scopeOfWork" in obj, get: obj => obj.scopeOfWork, set: (obj, value) => { obj.scopeOfWork = value; } }, metadata: _metadata }, _scopeOfWork_initializers, _scopeOfWork_extraInitializers);
        __esDecorate(null, null, _performanceBondRequired_decorators, { kind: "field", name: "performanceBondRequired", static: false, private: false, access: { has: obj => "performanceBondRequired" in obj, get: obj => obj.performanceBondRequired, set: (obj, value) => { obj.performanceBondRequired = value; } }, metadata: _metadata }, _performanceBondRequired_initializers, _performanceBondRequired_extraInitializers);
        __esDecorate(null, null, _paymentBondRequired_decorators, { kind: "field", name: "paymentBondRequired", static: false, private: false, access: { has: obj => "paymentBondRequired" in obj, get: obj => obj.paymentBondRequired, set: (obj, value) => { obj.paymentBondRequired = value; } }, metadata: _metadata }, _paymentBondRequired_initializers, _paymentBondRequired_extraInitializers);
        __esDecorate(null, null, _insuranceRequired_decorators, { kind: "field", name: "insuranceRequired", static: false, private: false, access: { has: obj => "insuranceRequired" in obj, get: obj => obj.insuranceRequired, set: (obj, value) => { obj.insuranceRequired = value; } }, metadata: _metadata }, _insuranceRequired_initializers, _insuranceRequired_extraInitializers);
        __esDecorate(null, null, _prevailingWageRequired_decorators, { kind: "field", name: "prevailingWageRequired", static: false, private: false, access: { has: obj => "prevailingWageRequired" in obj, get: obj => obj.prevailingWageRequired, set: (obj, value) => { obj.prevailingWageRequired = value; } }, metadata: _metadata }, _prevailingWageRequired_initializers, _prevailingWageRequired_extraInitializers);
        __esDecorate(null, null, _liquidatedDamagesRate_decorators, { kind: "field", name: "liquidatedDamagesRate", static: false, private: false, access: { has: obj => "liquidatedDamagesRate" in obj, get: obj => obj.liquidatedDamagesRate, set: (obj, value) => { obj.liquidatedDamagesRate = value; } }, metadata: _metadata }, _liquidatedDamagesRate_initializers, _liquidatedDamagesRate_extraInitializers);
        __esDecorate(null, null, _warrantyPeriod_decorators, { kind: "field", name: "warrantyPeriod", static: false, private: false, access: { has: obj => "warrantyPeriod" in obj, get: obj => obj.warrantyPeriod, set: (obj, value) => { obj.warrantyPeriod = value; } }, metadata: _metadata }, _warrantyPeriod_initializers, _warrantyPeriod_extraInitializers);
        __esDecorate(null, null, _metadata_decorators, { kind: "field", name: "metadata", static: false, private: false, access: { has: obj => "metadata" in obj, get: obj => obj.metadata, set: (obj, value) => { obj.metadata = value; } }, metadata: _metadata }, _metadata_initializers, _metadata_extraInitializers);
        __esDecorate(null, null, _createdBy_decorators, { kind: "field", name: "createdBy", static: false, private: false, access: { has: obj => "createdBy" in obj, get: obj => obj.createdBy, set: (obj, value) => { obj.createdBy = value; } }, metadata: _metadata }, _createdBy_initializers, _createdBy_extraInitializers);
        __esDecorate(null, null, _updatedBy_decorators, { kind: "field", name: "updatedBy", static: false, private: false, access: { has: obj => "updatedBy" in obj, get: obj => obj.updatedBy, set: (obj, value) => { obj.updatedBy = value; } }, metadata: _metadata }, _updatedBy_initializers, _updatedBy_extraInitializers);
        __esDecorate(null, null, _paymentApplications_decorators, { kind: "field", name: "paymentApplications", static: false, private: false, access: { has: obj => "paymentApplications" in obj, get: obj => obj.paymentApplications, set: (obj, value) => { obj.paymentApplications = value; } }, metadata: _metadata }, _paymentApplications_initializers, _paymentApplications_extraInitializers);
        __esDecorate(null, null, _amendments_decorators, { kind: "field", name: "amendments", static: false, private: false, access: { has: obj => "amendments" in obj, get: obj => obj.amendments, set: (obj, value) => { obj.amendments = value; } }, metadata: _metadata }, _amendments_initializers, _amendments_extraInitializers);
        __esDecorate(null, null, _milestones_decorators, { kind: "field", name: "milestones", static: false, private: false, access: { has: obj => "milestones" in obj, get: obj => obj.milestones, set: (obj, value) => { obj.milestones = value; } }, metadata: _metadata }, _milestones_initializers, _milestones_extraInitializers);
        __esDecorate(null, _classDescriptor = { value: _classThis }, _classDecorators, { kind: "class", name: _classThis.name, metadata: _metadata }, null, _classExtraInitializers);
        ConstructionContract = _classThis = _classDescriptor.value;
        if (_metadata) Object.defineProperty(_classThis, Symbol.metadata, { enumerable: true, configurable: true, writable: true, value: _metadata });
        __runInitializers(_classThis, _classExtraInitializers);
    })();
    return ConstructionContract = _classThis;
})();
exports.ConstructionContract = ConstructionContract;
//# sourceMappingURL=construction-contract.model.js.map