import { Model } from 'sequelize-typescript';
import { ClaimStatus, ClaimPriority } from '../types/warranty.types';
export declare class WarrantyClaim extends Model {
    id: number;
    warrantyId: number;
    claimNumber: string;
    title: string;
    description: string;
    issueDate: Date;
    reportedBy: string;
    reportedByContact: string;
    priority: ClaimPriority;
    component: string;
    location: string;
    defectDescription: string;
    rootCause?: string;
    estimatedCost: number;
    actualCost?: number;
    laborCost?: number;
    materialCost?: number;
    status: ClaimStatus;
    assignedTo?: string;
    assignedDate?: Date;
    reviewedBy?: string;
    reviewedDate?: Date;
    reviewNotes?: string;
    approvedBy?: string;
    approvedDate?: Date;
    rejectionReason?: string;
    resolutionDate?: Date;
    resolutionDescription?: string;
    photos: string[];
    documents: string[];
    callbackScheduled: boolean;
    callbackDate?: Date;
    completionDate?: Date;
    completionNotes?: string;
    satisfactionRating?: number;
    feedback?: string;
    escalated: boolean;
    escalationLevel: number;
    escalationReason?: string;
    disputeReason?: string;
    disputeResolution?: string;
    tags: string[];
    metadata: Record<string, any>;
    createdBy: string;
    updatedBy: string;
}
//# sourceMappingURL=warranty-claim.model.d.ts.map