/**
 * WF-COMP-319 | base-entities.ts - Base Entity Type Definitions
 * Purpose: Base interfaces and utility types for entity modeling
 * Upstream: Database models | Dependencies: None
 * Downstream: All entity types | Called by: Domain models
 * Related: All domain type modules
 * Exports: Base interfaces, utility types for CRUD operations
 * Last Updated: 2025-11-12 | File Type: .ts
 * Critical Path: Entity definition → Type validation → Data persistence
 * LLM Context: Base entity patterns extracted from common.ts for reusability
 */

/**
 * Base Entities Module
 *
 * Foundational interfaces and utility types for entity modeling.
 * All database entities should extend these base interfaces to ensure
 * consistent structure and behavior.
 *
 * @module types/core/base-entities
 * @category Types
 */

// ============================================================================
// BASE ENTITY INTERFACES
// ============================================================================

/**
 * Base entity interface with common database fields.
 *
 * All database entities extend this interface to ensure consistent
 * timestamps and identifier patterns.
 *
 * @property {string} id - Unique identifier (UUID v4)
 * @property {string} createdAt - ISO 8601 creation timestamp
 * @property {string} updatedAt - ISO 8601 last modification timestamp
 *
 * @example
 * ```typescript
 * interface MyEntity extends BaseEntity {
 *   name: string;
 *   description: string;
 * }
 * ```
 */
export interface BaseEntity {
  id: string;
  createdAt: string;
  updatedAt: string;
}

/**
 * Base interface for person entities (students, contacts, users).
 *
 * Provides common person properties that can be extended by specific
 * person entity types.
 *
 * @extends {BaseEntity}
 * @property {string} firstName - Person's first name
 * @property {string} lastName - Person's last name
 * @property {string} [email] - Email address (optional)
 * @property {string} [phone] - Phone number (optional)
 *
 * @example
 * ```typescript
 * interface Contact extends BasePersonEntity {
 *   relationship: string;
 *   priority: ContactPriority;
 * }
 * ```
 */
export interface BasePersonEntity extends BaseEntity {
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
}

/**
 * Base interface for entities with physical addresses.
 *
 * @property {string} [address] - Street address line
 * @property {string} [city] - City name
 * @property {string} [state] - State/province code
 * @property {string} [zipCode] - Postal/ZIP code
 * @property {string} [country] - Country name or code
 *
 * @example
 * ```typescript
 * interface School extends BaseEntity, BaseAddressEntity {
 *   name: string;
 *   district: string;
 * }
 * ```
 */
export interface BaseAddressEntity {
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
  country?: string;
}

/**
 * Base interface for auditable entities.
 *
 * Tracks who created and last modified the entity for audit trails.
 *
 * @extends {BaseEntity}
 * @property {string} [createdBy] - UUID of user who created entity
 * @property {string} [updatedBy] - UUID of user who last updated entity
 * @property {number} [version] - Optimistic locking version number
 *
 * @example
 * ```typescript
 * interface MedicalRecord extends BaseAuditEntity {
 *   studentId: string;
 *   diagnosis: string;
 *   treatment: string;
 * }
 * ```
 */
export interface BaseAuditEntity extends BaseEntity {
  createdBy?: string;
  updatedBy?: string;
  version?: number;
}

// ============================================================================
// UTILITY TYPES FOR CRUD OPERATIONS
// ============================================================================

/**
 * Type helper for create requests that omits auto-generated fields.
 *
 * Use this type when defining request bodies for entity creation.
 * It automatically removes fields that are generated by the database
 * (id, createdAt, updatedAt).
 *
 * @template T - The full entity type
 *
 * @example
 * ```typescript
 * interface Student extends BaseEntity {
 *   firstName: string;
 *   lastName: string;
 *   grade: string;
 * }
 *
 * type CreateStudentRequest = CreateRequest<Student>;
 * // Results in: { firstName: string; lastName: string; grade: string }
 * // Omits: id, createdAt, updatedAt
 * ```
 */
export type CreateRequest<T> = Omit<T, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Type helper for update requests that makes all fields optional and omits read-only fields.
 *
 * Use this type when defining request bodies for entity updates.
 * It makes all fields optional (allowing partial updates) and removes
 * fields that should not be modified by clients.
 *
 * @template T - The full entity type
 *
 * @example
 * ```typescript
 * interface Student extends BaseEntity {
 *   firstName: string;
 *   lastName: string;
 *   grade: string;
 * }
 *
 * type UpdateStudentRequest = UpdateRequest<Student>;
 * // Results in: { firstName?: string; lastName?: string; grade?: string }
 * // All fields optional, omits: id, createdAt, updatedAt
 * ```
 */
export type UpdateRequest<T> = Partial<Omit<T, 'id' | 'createdAt' | 'updatedAt'>>;

/**
 * Type helper for entities where timestamp fields are optional.
 *
 * Useful for form data or client-side entity creation before
 * the entity has been persisted to the database.
 *
 * @template T - The full entity type
 *
 * @example
 * ```typescript
 * interface Student extends BaseEntity {
 *   firstName: string;
 *   lastName: string;
 * }
 *
 * type StudentFormData = EntityWithOptionalDates<Student>;
 * // Results in entity with optional createdAt and updatedAt
 * ```
 */
export type EntityWithOptionalDates<T> = Omit<T, 'createdAt' | 'updatedAt'> & {
  createdAt?: string;
  updatedAt?: string;
};
