/**
 * WF-COMP-319 | utility-types.ts - TypeScript Utility Type Definitions
 * Purpose: Generic type transformations and helpers
 * Upstream: Base entities | Dependencies: None
 * Downstream: API services, forms, components | Called by: CRUD operations
 * Related: Base entities, API responses
 * Exports: CreateRequest, UpdateRequest, etc. | Key Features: Type transformations
 * Last Updated: 2025-11-12 | File Type: .ts
 * Critical Path: Form submission → Type transformation → API call → Response parsing
 * LLM Context: Utility types for common operations, part of type system refactoring
 */

/**
 * Utility Types Module
 *
 * Provides generic type transformations and helpers for common operations
 * like creating and updating entities. These utilities reduce boilerplate
 * and ensure consistent patterns across the application.
 *
 * @module types/core/utility-types
 * @category Types
 */

/**
 * Type helper for create requests that omits auto-generated fields.
 *
 * Removes fields that are automatically generated by the backend
 * (id, createdAt, updatedAt) to create a clean input type for entity creation.
 *
 * @template T - The full entity type
 *
 * @example
 * ```typescript
 * interface Student extends BaseEntity {
 *   firstName: string;
 *   lastName: string;
 *   grade: string;
 * }
 *
 * type CreateStudentRequest = CreateRequest<Student>;
 * // Result: { firstName: string; lastName: string; grade: string; }
 * // Omits: id, createdAt, updatedAt
 * ```
 */
export type CreateRequest<T> = Omit<T, 'id' | 'createdAt' | 'updatedAt'>;

/**
 * Type helper for update requests that makes all fields optional and omits read-only fields.
 *
 * Creates a partial type for updates where all fields are optional,
 * excluding auto-generated and read-only fields.
 *
 * @template T - The full entity type
 *
 * @example
 * ```typescript
 * interface Student extends BaseEntity {
 *   firstName: string;
 *   lastName: string;
 *   grade: string;
 *   isActive: boolean;
 * }
 *
 * type UpdateStudentRequest = UpdateRequest<Student>;
 * // Result: { firstName?: string; lastName?: string; grade?: string; isActive?: boolean; }
 * // All fields optional except: id, createdAt, updatedAt (omitted)
 * ```
 */
export type UpdateRequest<T> = Partial<Omit<T, 'id' | 'createdAt' | 'updatedAt'>>;

/**
 * Type helper for entities where timestamp fields are optional.
 *
 * Useful for frontend forms and DTOs where timestamp fields
 * haven't been populated yet.
 *
 * @template T - The full entity type
 *
 * @example
 * ```typescript
 * interface Student extends BaseEntity {
 *   firstName: string;
 *   lastName: string;
 * }
 *
 * type StudentDTO = EntityWithOptionalDates<Student>;
 * // Result: { id: string; firstName: string; lastName: string; createdAt?: string; updatedAt?: string; }
 * ```
 */
export type EntityWithOptionalDates<T> = Omit<T, 'createdAt' | 'updatedAt'> & {
  createdAt?: string;
  updatedAt?: string;
};
