/**
 * @fileoverview GraphQL Types Index
 *
 * Centralized exports for all GraphQL TypeScript types.
 * Types are manually defined for immediate use and will be replaced
 * by graphql-codegen generated types in the future.
 *
 * @module graphql/types
 * @since 1.0.0
 *
 * @remarks
 * Current approach: Manual type definitions
 * Future: Types generated by graphql-codegen from schema and operations
 *
 * @example
 * ```typescript
 * import { Student, Contact, PageInfo } from '@/graphql/types';
 *
 * const student: Student = {
 *   id: '123',
 *   firstName: 'John',
 *   lastName: 'Doe',
 *   // ...
 * };
 * ```
 */

// Generated types will be exported from here after running codegen
// export * from './generated';

/**
 * Manual type definitions for immediate use
 * These will be replaced by generated types
 */

/**
 * Student entity representing a student in the school health system.
 *
 * @property {string} id - Unique student identifier
 * @property {string} studentNumber - School-assigned student number
 * @property {string} firstName - Student's first name
 * @property {string} lastName - Student's last name
 * @property {string} fullName - Computed full name (firstName + lastName)
 * @property {string} dateOfBirth - Student's date of birth (ISO 8601)
 * @property {string} grade - Current grade level
 * @property {'MALE' | 'FEMALE' | 'OTHER' | 'PREFER_NOT_TO_SAY'} gender - Student's gender
 * @property {string | null} [photo] - URL to student photo
 * @property {string | null} [medicalRecordNum] - Medical record number if applicable
 * @property {boolean} isActive - Whether student is currently enrolled
 * @property {string} enrollmentDate - Date of enrollment (ISO 8601)
 * @property {string | null} [nurseId] - ID of assigned nurse
 * @property {string} createdAt - Record creation timestamp (ISO 8601)
 * @property {string} updatedAt - Last update timestamp (ISO 8601)
 */
export interface Student {
  id: string;
  studentNumber: string;
  firstName: string;
  lastName: string;
  fullName: string;
  dateOfBirth: string;
  grade: string;
  gender: 'MALE' | 'FEMALE' | 'OTHER' | 'PREFER_NOT_TO_SAY';
  photo?: string | null;
  medicalRecordNum?: string | null;
  isActive: boolean;
  enrollmentDate: string;
  nurseId?: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Contact entity representing emergency contacts, guardians, staff, and providers.
 *
 * @property {string} id - Unique contact identifier
 * @property {string} firstName - Contact's first name
 * @property {string} lastName - Contact's last name
 * @property {string} fullName - Computed full name (firstName + lastName)
 * @property {string} displayName - Preferred display name
 * @property {string | null} [email] - Email address
 * @property {string | null} [phone] - Phone number
 * @property {'guardian' | 'staff' | 'vendor' | 'provider' | 'other'} type - Contact type
 * @property {string | null} [organization] - Organization name
 * @property {string | null} [title] - Professional title
 * @property {string | null} [address] - Street address
 * @property {string | null} [city] - City
 * @property {string | null} [state] - State/Province
 * @property {string | null} [zip] - Postal code
 * @property {string | null} [relationTo] - ID of related entity (e.g., student ID)
 * @property {string | null} [relationshipType] - Type of relationship (e.g., 'parent', 'guardian')
 * @property {any} [customFields] - Additional custom data
 * @property {boolean} isActive - Whether contact is active
 * @property {string | null} [notes] - Additional notes
 * @property {string} createdAt - Record creation timestamp (ISO 8601)
 * @property {string} updatedAt - Last update timestamp (ISO 8601)
 */
export interface Contact {
  id: string;
  firstName: string;
  lastName: string;
  fullName: string;
  displayName: string;
  email?: string | null;
  phone?: string | null;
  type: 'guardian' | 'staff' | 'vendor' | 'provider' | 'other';
  organization?: string | null;
  title?: string | null;
  address?: string | null;
  city?: string | null;
  state?: string | null;
  zip?: string | null;
  relationTo?: string | null;
  relationshipType?: string | null;
  customFields?: any;
  isActive: boolean;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
}

/**
 * Medication entity representing prescribed medications for students.
 *
 * @property {string} id - Unique medication record identifier
 * @property {string} studentId - ID of student taking medication
 * @property {string} medicationName - Brand name of medication
 * @property {string | null} [genericName] - Generic drug name
 * @property {string} dosage - Dosage amount
 * @property {string} unit - Unit of measurement (e.g., 'mg', 'ml')
 * @property {string} frequency - How often medication is taken
 * @property {string} route - Administration route (e.g., 'oral', 'topical')
 * @property {string | null} [prescribedBy] - Prescribing physician
 * @property {string | null} [prescriptionDate] - Date prescribed (ISO 8601)
 * @property {string} startDate - Treatment start date (ISO 8601)
 * @property {string | null} [endDate] - Treatment end date if applicable (ISO 8601)
 * @property {string | null} [reason] - Reason for prescription
 * @property {string | null} [specialInstructions] - Administration instructions
 * @property {boolean} isActive - Whether medication is currently active
 * @property {boolean} isControlled - Whether medication is a controlled substance
 * @property {boolean} requiresRefrigeration - Storage requirement flag
 * @property {string} createdAt - Record creation timestamp (ISO 8601)
 * @property {string} updatedAt - Last update timestamp (ISO 8601)
 */
export interface Medication {
  id: string;
  studentId: string;
  medicationName: string;
  genericName?: string | null;
  dosage: string;
  unit: string;
  frequency: string;
  route: string;
  prescribedBy?: string | null;
  prescriptionDate?: string | null;
  startDate: string;
  endDate?: string | null;
  reason?: string | null;
  specialInstructions?: string | null;
  isActive: boolean;
  isControlled: boolean;
  requiresRefrigeration: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * Pagination information for paginated GraphQL queries.
 *
 * @property {number} page - Current page number (1-based)
 * @property {number} limit - Items per page
 * @property {number} total - Total number of items across all pages
 * @property {number} totalPages - Total number of pages
 */
export interface PageInfo {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
}

/**
 * Generic paginated response wrapper.
 *
 * @template T - Type of items in the paginated response
 * @property {T[]} items - Array of items for current page
 * @property {PageInfo} pagination - Pagination metadata
 */
export interface PaginatedResponse<T> {
  items: T[];
  pagination: PageInfo;
}

/**
 * Paginated response for student queries.
 *
 * @property {Student[]} students - Array of student records
 * @property {PageInfo} pagination - Pagination metadata
 */
export interface StudentListResponse {
  students: Student[];
  pagination: PageInfo;
}

/**
 * Paginated response for contact queries.
 *
 * @property {Contact[]} contacts - Array of contact records
 * @property {PageInfo} pagination - Pagination metadata
 */
export interface ContactListResponse {
  contacts: Contact[];
  pagination: PageInfo;
}

/**
 * Paginated response for medication queries.
 *
 * @property {Medication[]} medications - Array of medication records
 * @property {PageInfo} pagination - Pagination metadata
 */
export interface MedicationListResponse {
  medications: Medication[];
  pagination: PageInfo;
}

/**
 * Standard response for delete mutations.
 *
 * @property {boolean} success - Whether deletion was successful
 * @property {string} message - Human-readable result message
 */
export interface DeleteResponse {
  success: boolean;
  message: string;
}

/**
 * GraphQLErrorResponse is exported from '@/graphql/utils/errorHandler'
 *
 * This type is defined in the errorHandler utility module and includes
 * additional properties like statusCode. Import it from there or from
 * the main graphql module to avoid duplication.
 *
 * @see {@link module:graphql/utils/errorHandler}
 */
