export enum MessageCategory {
  GENERAL = 'GENERAL',
  APPOINTMENT = 'APPOINTMENT',
  MEDICATION = 'MEDICATION',
  EMERGENCY = 'EMERGENCY',
  INJURY_REPORT = 'INJURY_REPORT',
  IMMUNIZATION = 'IMMUNIZATION',
  CONSENT_FORM = 'CONSENT_FORM',
  SURVEY = 'SURVEY',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  REMINDER = 'REMINDER',
}
