/**
 * LOC: REGCMP001
 * File: /reuse/edwards/financial/composites/regulatory-compliance-reporting-composite.ts
 *
 * UPSTREAM (imports from):
 *   - ../audit-trail-compliance-kit
 *   - ../financial-reporting-analytics-kit
 *   - ../financial-close-automation-kit
 *   - ../intercompany-accounting-kit
 *   - ../revenue-recognition-billing-kit
 *
 * DOWNSTREAM (imported by):
 *   - Regulatory compliance REST API controllers
 *   - SOX compliance services
 *   - Disclosure management services
 *   - Control testing services
 *   - Compliance dashboard services
 */
import { type AuditEntry, type ComplianceReport, type ControlTest, type ControlDeficiency } from '../audit-trail-compliance-kit';
import { type BalanceSheetReport, type IncomeStatementReport, type CashFlowStatement, type FinancialFootnote } from '../financial-reporting-analytics-kit';
import { type RevenueCompliance, type RevenueDisclosure } from '../revenue-recognition-billing-kit';
/**
 * Regulatory compliance API configuration
 */
export interface RegulatoryApiConfig {
    baseUrl: string;
    enableSOXCompliance: boolean;
    enableGAAPReporting: boolean;
    enableIFRSReporting: boolean;
    autoGenerateDisclosures: boolean;
    controlTestingFrequency: 'monthly' | 'quarterly' | 'annual';
}
/**
 * SOX compliance assessment
 */
export interface SOXComplianceAssessment {
    assessmentId: string;
    entityId: number;
    assessmentDate: Date;
    fiscalYear: number;
    overallRating: 'effective' | 'effective_with_deficiencies' | 'ineffective';
    entityLevelControls: ControlAssessment;
    processLevelControls: ControlAssessment;
    itGeneralControls: ControlAssessment;
    materialWeaknesses: ControlDeficiency[];
    significantDeficiencies: ControlDeficiency[];
    remediationPlan: RemediationPlan;
}
/**
 * Control assessment
 */
export interface ControlAssessment {
    totalControls: number;
    controlsTested: number;
    effectiveControls: number;
    ineffectiveControls: number;
    effectiveness: number;
    deficiencies: ControlDeficiency[];
}
/**
 * Remediation plan
 */
export interface RemediationPlan {
    planId: string;
    deficiencies: ControlDeficiency[];
    remediationActions: RemediationAction[];
    targetCompletionDate: Date;
    status: 'planned' | 'in_progress' | 'completed';
}
/**
 * Remediation action
 */
export interface RemediationAction {
    actionId: string;
    deficiencyId: string;
    description: string;
    owner: string;
    dueDate: Date;
    status: 'open' | 'in_progress' | 'completed' | 'overdue';
    completionDate?: Date;
}
/**
 * GAAP/IFRS compliance report
 */
export interface AccountingStandardsComplianceReport {
    reportId: string;
    entityId: number;
    standard: 'GAAP' | 'IFRS';
    reportDate: Date;
    fiscalYear: number;
    fiscalPeriod: number;
    compliant: boolean;
    financialStatements: {
        balanceSheet: BalanceSheetReport;
        incomeStatement: IncomeStatementReport;
        cashFlow: CashFlowStatement;
    };
    disclosures: FinancialFootnote[];
    complianceChecks: ComplianceCheck[];
    exceptions: ComplianceException[];
}
/**
 * Compliance check
 */
export interface ComplianceCheck {
    checkId: string;
    checkName: string;
    requirement: string;
    status: 'pass' | 'fail' | 'warning';
    details: string;
    references: string[];
}
/**
 * Compliance exception
 */
export interface ComplianceException {
    exceptionId: string;
    exceptionType: string;
    severity: 'low' | 'medium' | 'high' | 'critical';
    description: string;
    impact: string;
    resolution: string;
    dueDate: Date;
}
/**
 * Regulatory filing
 */
export interface RegulatoryFiling {
    filingId: string;
    filingType: '10-K' | '10-Q' | '8-K' | 'S-1' | 'DEF-14A' | 'Other';
    entityId: number;
    fiscalYear: number;
    fiscalPeriod?: number;
    filingDate?: Date;
    dueDate: Date;
    status: 'draft' | 'review' | 'approved' | 'filed';
    financialStatements: any;
    disclosures: any[];
    exhibits: any[];
    certifications: Certification[];
}
/**
 * Certification
 */
export interface Certification {
    certificationId: string;
    certificationType: 'CEO' | 'CFO' | 'Controller' | 'Auditor';
    certifier: string;
    certificationDate: Date;
    statementText: string;
    signature?: string;
}
/**
 * Disclosure requirement
 */
export interface DisclosureRequirement {
    requirementId: string;
    disclosureType: string;
    standard: 'GAAP' | 'IFRS' | 'SEC' | 'PCAOB';
    description: string;
    required: boolean;
    frequency: 'annual' | 'quarterly' | 'event-driven';
    templateAvailable: boolean;
}
/**
 * Compliance dashboard
 */
export interface ComplianceDashboard {
    dashboardId: string;
    entityId: number;
    lastUpdated: Date;
    soxCompliance: {
        overallStatus: string;
        controlsEffective: number;
        openDeficiencies: number;
        upcomingTests: number;
    };
    financialReporting: {
        gaapCompliant: boolean;
        ifrsCompliant: boolean;
        pendingDisclosures: number;
        lastAudit: Date;
    };
    regulatoryFilings: {
        upcomingFilings: number;
        overdueFilings: number;
        recentFilings: RegulatoryFiling[];
    };
    auditFindings: {
        materialWeaknesses: number;
        significantDeficiencies: number;
        openRemediation: number;
    };
}
/**
 * Conducts comprehensive SOX 404 compliance assessment
 * Composes: testInternalControl, assessControlEffectiveness, identifyControlDeficiency, generateComplianceReport
 *
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @param userId - User conducting assessment
 * @returns SOX compliance assessment
 */
export declare const conductComprehensiveSOXAssessment: (entityId: number, fiscalYear: number, userId: string) => Promise<{
    assessment: SOXComplianceAssessment;
    report: ComplianceReport;
    audit: AuditEntry;
}>;
/**
 * Tests internal control with documentation
 * Composes: testInternalControl, documentControlTest, assessControlEffectiveness
 *
 * @param controlId - Control identifier
 * @param userId - User testing control
 * @returns Control test result
 */
export declare const testInternalControlWithDocumentation: (controlId: string, userId: string) => Promise<{
    test: ControlTest;
    documentation: any;
    effectiveness: any;
    audit: AuditEntry;
}>;
/**
 * Tracks control deficiency remediation
 * Composes: identifyControlDeficiency, trackControlRemediation, assessControlEffectiveness
 *
 * @param deficiencyId - Deficiency identifier
 * @param remediationActions - Remediation actions
 * @param userId - User tracking remediation
 * @returns Remediation tracking result
 */
export declare const trackControlDeficiencyRemediation: (deficiencyId: string, remediationActions: Partial<RemediationAction>[], userId: string) => Promise<{
    deficiency: ControlDeficiency;
    remediation: any;
    retestRequired: boolean;
    audit: AuditEntry;
}>;
/**
 * Validates segregation of duties
 * Composes: validateSegregationOfDuties, enforceAccessControls, identifySODConflicts
 *
 * @param entityId - Entity identifier
 * @param userId - User validating SOD
 * @returns SOD validation result
 */
export declare const validateSegregationOfDutiesCompliance: (entityId: number, userId: string) => Promise<{
    validation: any;
    conflicts: any[];
    recommendations: string[];
    audit: AuditEntry;
}>;
/**
 * Generates GAAP-compliant financial statements
 * Composes: generateBalanceSheet, generateIncomeStatement, generateCashFlowStatement, validateFinancialReport
 *
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @param fiscalPeriod - Fiscal period
 * @param userId - User generating statements
 * @returns GAAP-compliant financial statements
 */
export declare const generateGAAPCompliantFinancialStatements: (entityId: number, fiscalYear: number, fiscalPeriod: number, userId: string) => Promise<{
    complianceReport: AccountingStandardsComplianceReport;
    disclosures: FinancialFootnote[];
    validation: boolean;
    audit: AuditEntry;
}>;
/**
 * Generates IFRS-compliant financial statements
 * Composes: generateBalanceSheet, generateIncomeStatement, generateCashFlowStatement, validateFinancialReport
 *
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @param fiscalPeriod - Fiscal period
 * @param userId - User generating statements
 * @returns IFRS-compliant financial statements
 */
export declare const generateIFRSCompliantFinancialStatements: (entityId: number, fiscalYear: number, fiscalPeriod: number, userId: string) => Promise<{
    complianceReport: AccountingStandardsComplianceReport;
    disclosures: FinancialFootnote[];
    validation: boolean;
    audit: AuditEntry;
}>;
/**
 * Validates revenue recognition compliance
 * Composes: validateRevenueRecognition, assessRevenueCompliance, generateRevenueDisclosure
 *
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @returns Revenue recognition compliance
 */
export declare const validateRevenueRecognitionCompliance: (entityId: number, fiscalYear: number) => Promise<{
    validation: any;
    compliance: RevenueCompliance;
    disclosure: RevenueDisclosure;
}>;
/**
 * Prepares comprehensive regulatory filing
 * Composes: generateFinancialStatements, generateDisclosures, validateFiling, createCertifications
 *
 * @param filingType - Filing type
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @param userId - User preparing filing
 * @returns Regulatory filing
 */
export declare const prepareComprehensiveRegulatoryFiling: (filingType: RegulatoryFiling["filingType"], entityId: number, fiscalYear: number, userId: string) => Promise<{
    filing: RegulatoryFiling;
    validation: any;
    certifications: Certification[];
    audit: AuditEntry;
}>;
/**
 * Submits regulatory filing electronically
 * Composes: validateFiling, submitElectronicFiling, recordFilingConfirmation
 *
 * @param filingId - Filing identifier
 * @param userId - User submitting filing
 * @returns Filing submission result
 */
export declare const submitRegulatoryFilingElectronically: (filingId: string, userId: string) => Promise<{
    submitted: boolean;
    confirmationNumber: string;
    submissionDate: Date;
    audit: AuditEntry;
}>;
/**
 * Manages disclosure requirements and generation
 * Composes: identifyDisclosureRequirements, generateDisclosures, validateDisclosures
 *
 * @param entityId - Entity identifier
 * @param standard - Accounting standard
 * @param fiscalYear - Fiscal year
 * @returns Disclosure management result
 */
export declare const manageComprehensiveDisclosures: (entityId: number, standard: "GAAP" | "IFRS", fiscalYear: number) => Promise<{
    requirements: DisclosureRequirement[];
    disclosures: FinancialFootnote[];
    missing: DisclosureRequirement[];
    validation: any;
}>;
/**
 * Generates automated disclosure content
 * Composes: generateFootnotes with templates and data
 *
 * @param disclosureType - Disclosure type
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @returns Generated disclosure
 */
export declare const generateAutomatedDisclosureContent: (disclosureType: string, entityId: number, fiscalYear: number) => Promise<FinancialFootnote>;
/**
 * Generates comprehensive compliance dashboard
 * Composes: Multiple compliance status checks
 *
 * @param entityId - Entity identifier
 * @returns Compliance dashboard
 */
export declare const generateComprehensiveComplianceDashboard: (entityId: number) => Promise<ComplianceDashboard>;
/**
 * Monitors compliance in real-time
 * Composes: Multiple monitoring functions
 *
 * @param entityId - Entity identifier
 * @returns Real-time compliance monitoring
 */
export declare const monitorComplianceRealTime: (entityId: number) => Promise<{
    dashboard: ComplianceDashboard;
    alerts: any[];
    trends: any[];
}>;
/**
 * Prepares comprehensive audit package
 * Composes: getAuditTrail, generateFinancialStatements, documentInternalControls
 *
 * @param entityId - Entity identifier
 * @param fiscalYear - Fiscal year
 * @param userId - User preparing package
 * @returns Audit package
 */
export declare const prepareComprehensiveAuditPackage: (entityId: number, fiscalYear: number, userId: string) => Promise<{
    financialStatements: any;
    auditTrail: AuditEntry[];
    controlDocumentation: any[];
    supportingDocuments: any[];
    audit: AuditEntry;
}>;
/**
 * Generates audit report with findings
 * Composes: generateAuditReport, documentFindings, trackRemediation
 *
 * @param entityId - Entity identifier
 * @param auditType - Audit type
 * @param fiscalYear - Fiscal year
 * @returns Audit report
 */
export declare const generateComprehensiveAuditReport: (entityId: number, auditType: string, fiscalYear: number) => Promise<{
    report: any;
    findings: any[];
    recommendations: string[];
}>;
export { conductComprehensiveSOXAssessment, testInternalControlWithDocumentation, trackControlDeficiencyRemediation, validateSegregationOfDutiesCompliance, generateGAAPCompliantFinancialStatements, generateIFRSCompliantFinancialStatements, validateRevenueRecognitionCompliance, prepareComprehensiveRegulatoryFiling, submitRegulatoryFilingElectronically, manageComprehensiveDisclosures, generateAutomatedDisclosureContent, generateComprehensiveComplianceDashboard, monitorComplianceRealTime, prepareComprehensiveAuditPackage, generateComprehensiveAuditReport, type RegulatoryApiConfig, type SOXComplianceAssessment, type ControlAssessment, type RemediationPlan, type RemediationAction, type AccountingStandardsComplianceReport, type ComplianceCheck, type ComplianceException, type RegulatoryFiling, type Certification, type DisclosureRequirement, type ComplianceDashboard, };
//# sourceMappingURL=regulatory-compliance-reporting-composite.d.ts.map