/**
 * @fileoverview Incident CRUD Schemas
 * @module schemas/incidents/incident.crud
 *
 * Create, Read, Update schemas for incident operations.
 * Includes discriminated union of all incident types for type-safe operations.
 */

import { z } from 'zod';
import { BaseIncidentSchema } from './incident.base.schemas';
import {
  InjuryIncidentSchema,
  IllnessIncidentSchema,
  BehavioralIncidentSchema,
  SafetyIncidentSchema,
  EmergencyIncidentSchema,
} from './incident.types.schemas';

// ==========================================
// DISCRIMINATED UNION - ALL INCIDENT TYPES
// ==========================================

/**
 * Discriminated Union of All Incident Types
 *
 * @remarks
 * This union type allows TypeScript to narrow the incident type based on the 'type' field.
 * Enables type-safe handling of different incident types with their specific fields.
 *
 * @example
 * ```typescript
 * function handleIncident(incident: Incident) {
 *   if (incident.type === 'INJURY') {
 *     // TypeScript knows incident has injuryType, injuryLocation, etc.
 *     console.log(incident.injuryType);
 *   } else if (incident.type === 'BEHAVIORAL') {
 *     // TypeScript knows incident has behaviorType, triggers, etc.
 *     console.log(incident.behaviorType);
 *   }
 * }
 * ```
 */
export const IncidentSchema = z.discriminatedUnion('type', [
  InjuryIncidentSchema,
  IllnessIncidentSchema,
  BehavioralIncidentSchema,
  SafetyIncidentSchema,
  EmergencyIncidentSchema,
  BaseIncidentSchema, // Fallback for other types
]);

export type Incident = z.infer<typeof IncidentSchema>;

// ==========================================
// CREATE INCIDENT SCHEMA
// ==========================================

/**
 * Create Incident Schema
 *
 * @remarks
 * Excludes auto-generated and system-managed fields:
 * - id: Generated by database
 * - incidentNumber: Auto-generated sequence
 * - createdAt/updatedAt: Timestamp management
 * - createdBy/updatedBy: Set by system from auth context
 *
 * Use this schema for validating new incident creation requests.
 */
export const CreateIncidentSchema = BaseIncidentSchema.omit({
  id: true,
  incidentNumber: true,
  createdAt: true,
  updatedAt: true,
  createdBy: true,
  updatedBy: true,
});

export type CreateIncidentInput = z.infer<typeof CreateIncidentSchema>;

/**
 * Type-specific Create Schemas
 * For strict validation when creating specific incident types
 */
export const CreateInjuryIncidentSchema = InjuryIncidentSchema.omit({
  id: true,
  incidentNumber: true,
  createdAt: true,
  updatedAt: true,
  createdBy: true,
  updatedBy: true,
});

export const CreateIllnessIncidentSchema = IllnessIncidentSchema.omit({
  id: true,
  incidentNumber: true,
  createdAt: true,
  updatedAt: true,
  createdBy: true,
  updatedBy: true,
});

export const CreateBehavioralIncidentSchema = BehavioralIncidentSchema.omit({
  id: true,
  incidentNumber: true,
  createdAt: true,
  updatedAt: true,
  createdBy: true,
  updatedBy: true,
});

export const CreateSafetyIncidentSchema = SafetyIncidentSchema.omit({
  id: true,
  incidentNumber: true,
  createdAt: true,
  updatedAt: true,
  createdBy: true,
  updatedBy: true,
});

export const CreateEmergencyIncidentSchema = EmergencyIncidentSchema.omit({
  id: true,
  incidentNumber: true,
  createdAt: true,
  updatedAt: true,
  createdBy: true,
  updatedBy: true,
});

export type CreateInjuryIncidentInput = z.infer<typeof CreateInjuryIncidentSchema>;
export type CreateIllnessIncidentInput = z.infer<typeof CreateIllnessIncidentSchema>;
export type CreateBehavioralIncidentInput = z.infer<typeof CreateBehavioralIncidentSchema>;
export type CreateSafetyIncidentInput = z.infer<typeof CreateSafetyIncidentSchema>;
export type CreateEmergencyIncidentInput = z.infer<typeof CreateEmergencyIncidentSchema>;

// ==========================================
// UPDATE INCIDENT SCHEMA
// ==========================================

/**
 * Update Incident Schema
 *
 * @remarks
 * Allows partial updates to any incident field except system-managed timestamps.
 * Requires:
 * - id: Identifies which incident to update
 * - updatedBy: Tracks who made the change (audit trail)
 *
 * All other fields are optional to support partial updates.
 *
 * @example
 * ```typescript
 * // Update only status
 * const update: UpdateIncidentInput = {
 *   id: 'abc-123',
 *   status: 'RESOLVED',
 *   updatedBy: 'user-456'
 * };
 *
 * // Update multiple fields
 * const update2: UpdateIncidentInput = {
 *   id: 'abc-123',
 *   status: 'UNDER_INVESTIGATION',
 *   severity: 'SERIOUS',
 *   followUpNotes: 'Additional investigation required',
 *   updatedBy: 'user-456'
 * };
 * ```
 */
export const UpdateIncidentSchema = BaseIncidentSchema.partial().extend({
  id: z.string().uuid(),
  updatedBy: z.string().uuid(),
});

export type UpdateIncidentInput = z.infer<typeof UpdateIncidentSchema>;

// ==========================================
// PATCH INCIDENT SCHEMA
// ==========================================

/**
 * Patch Incident Schema
 *
 * @remarks
 * Minimal update schema for quick status/severity changes.
 * Useful for workflows that only need to update specific fields.
 */
export const PatchIncidentSchema = z.object({
  id: z.string().uuid(),
  status: z.enum(['PENDING_REVIEW', 'UNDER_INVESTIGATION', 'REQUIRES_ACTION', 'RESOLVED', 'ARCHIVED']).optional(),
  severity: z.enum(['MINOR', 'MODERATE', 'SERIOUS', 'CRITICAL', 'LIFE_THREATENING']).optional(),
  followUpNotes: z.string().max(2000).optional(),
  updatedBy: z.string().uuid(),
});

export type PatchIncidentInput = z.infer<typeof PatchIncidentSchema>;
