export declare enum CloseoutStatus {
    INITIATED = "INITIATED",
    PUNCH_LIST_IN_PROGRESS = "PUNCH_LIST_IN_PROGRESS",
    FINAL_INSPECTION_SCHEDULED = "FINAL_INSPECTION_SCHEDULED",
    FINAL_INSPECTION_COMPLETE = "FINAL_INSPECTION_COMPLETE",
    DOCUMENTATION_IN_PROGRESS = "DOCUMENTATION_IN_PROGRESS",
    OWNER_TRAINING_SCHEDULED = "OWNER_TRAINING_SCHEDULED",
    OWNER_TRAINING_COMPLETE = "OWNER_TRAINING_COMPLETE",
    WARRANTY_DOCUMENTATION_PENDING = "WARRANTY_DOCUMENTATION_PENDING",
    FINAL_PAYMENT_PENDING = "FINAL_PAYMENT_PENDING",
    LIEN_RELEASE_PENDING = "LIEN_RELEASE_PENDING",
    SUBSTANTIALLY_COMPLETE = "SUBSTANTIALLY_COMPLETE",
    FULLY_COMPLETE = "FULLY_COMPLETE",
    ON_HOLD = "ON_HOLD",
    CANCELLED = "CANCELLED"
}
export declare enum PunchListItemStatus {
    OPEN = "OPEN",
    IN_PROGRESS = "IN_PROGRESS",
    READY_FOR_REVIEW = "READY_FOR_REVIEW",
    REVIEWED = "REVIEWED",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    CLOSED = "CLOSED",
    CANCELLED = "CANCELLED"
}
export declare enum PunchListItemPriority {
    CRITICAL = "CRITICAL",
    HIGH = "HIGH",
    MEDIUM = "MEDIUM",
    LOW = "LOW"
}
export declare enum PunchListItemCategory {
    SAFETY = "SAFETY",
    CODE_COMPLIANCE = "CODE_COMPLIANCE",
    QUALITY = "QUALITY",
    FINISH = "FINISH",
    FUNCTIONAL = "FUNCTIONAL",
    COSMETIC = "COSMETIC",
    DOCUMENTATION = "DOCUMENTATION",
    WARRANTY = "WARRANTY",
    OTHER = "OTHER"
}
export declare enum CloseoutDocumentType {
    AS_BUILT_DRAWING = "AS_BUILT_DRAWING",
    OM_MANUAL = "OM_MANUAL",
    WARRANTY_CERTIFICATE = "WARRANTY_CERTIFICATE",
    EQUIPMENT_WARRANTY = "EQUIPMENT_WARRANTY",
    MATERIAL_WARRANTY = "MATERIAL_WARRANTY",
    TRAINING_MATERIAL = "TRAINING_MATERIAL",
    TRAINING_CERTIFICATE = "TRAINING_CERTIFICATE",
    INSPECTION_REPORT = "INSPECTION_REPORT",
    CERTIFICATE_OF_OCCUPANCY = "CERTIFICATE_OF_OCCUPANCY",
    LIEN_RELEASE = "LIEN_RELEASE",
    FINAL_PAYMENT_APPLICATION = "FINAL_PAYMENT_APPLICATION",
    CLOSEOUT_CHECKLIST = "CLOSEOUT_CHECKLIST",
    LESSONS_LEARNED = "LESSONS_LEARNED",
    FINAL_PROJECT_REPORT = "FINAL_PROJECT_REPORT",
    ATTIC_STOCK = "ATTIC_STOCK",
    KEYING_SCHEDULE = "KEYING_SCHEDULE",
    COMMISSIONING_REPORT = "COMMISSIONING_REPORT",
    TEST_REPORT = "TEST_REPORT",
    OTHER = "OTHER"
}
export declare enum DocumentStatus {
    PENDING = "PENDING",
    IN_PROGRESS = "IN_PROGRESS",
    SUBMITTED = "SUBMITTED",
    UNDER_REVIEW = "UNDER_REVIEW",
    APPROVED = "APPROVED",
    REJECTED = "REJECTED",
    DELIVERED = "DELIVERED",
    ACKNOWLEDGED = "ACKNOWLEDGED"
}
export declare enum InspectionResult {
    PASSED = "PASSED",
    PASSED_WITH_CONDITIONS = "PASSED_WITH_CONDITIONS",
    FAILED = "FAILED",
    PENDING = "PENDING",
    CANCELLED = "CANCELLED"
}
export declare enum TrainingStatus {
    SCHEDULED = "SCHEDULED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED = "COMPLETED",
    RESCHEDULED = "RESCHEDULED",
    CANCELLED = "CANCELLED"
}
export declare enum PaymentStatus {
    PENDING = "PENDING",
    APPROVED = "APPROVED",
    PROCESSED = "PROCESSED",
    PAID = "PAID",
    REJECTED = "REJECTED",
    ON_HOLD = "ON_HOLD"
}
//# sourceMappingURL=closeout.types.d.ts.map