
export enum QualityPlanStatus {
  DRAFT = 'DRAFT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum InspectionType {
  PRE_CONSTRUCTION = 'PRE_CONSTRUCTION',
  IN_PROGRESS = 'IN_PROGRESS',
  FINAL = 'FINAL',
  MILESTONE = 'MILESTONE',
  RANDOM = 'RANDOM',
  COMPLIANCE = 'COMPLIANCE',
  MATERIAL = 'MATERIAL',
  WORKMANSHIP = 'WORKMANSHIP',
}

export enum InspectionStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  CONDITIONAL_PASS = 'CONDITIONAL_PASS',
  CANCELLED = 'CANCELLED',
}

export enum DeficiencyStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
  VERIFIED = 'VERIFIED',
  CLOSED = 'CLOSED',
  ESCALATED = 'ESCALATED',
  REJECTED = 'REJECTED',
}

export enum DeficiencySeverity {
  CRITICAL = 'CRITICAL',
  MAJOR = 'MAJOR',
  MINOR = 'MINOR',
  COSMETIC = 'COSMETIC',
}

export enum TestingStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  RETESTING = 'RETESTING',
}
