/**
 * Common Enums
 * Shared enumerations used across the application
 */

/**
 * Health Record Types
 * Defines the types of health records that can be created
 */
export enum HealthRecordType {
  CHECKUP = 'CHECKUP',
  VACCINATION = 'VACCINATION',
  ILLNESS = 'ILLNESS',
  INJURY = 'INJURY',
  SCREENING = 'SCREENING',
  PHYSICAL_EXAM = 'PHYSICAL_EXAM',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  DENTAL = 'DENTAL',
  VISION = 'VISION',
  HEARING = 'HEARING',
  EXAMINATION = 'EXAMINATION',
  ALLERGY_DOCUMENTATION = 'ALLERGY_DOCUMENTATION',
  CHRONIC_CONDITION_REVIEW = 'CHRONIC_CONDITION_REVIEW',
  GROWTH_ASSESSMENT = 'GROWTH_ASSESSMENT',
  VITAL_SIGNS_CHECK = 'VITAL_SIGNS_CHECK',
  EMERGENCY_VISIT = 'EMERGENCY_VISIT',
  FOLLOW_UP = 'FOLLOW_UP',
  CONSULTATION = 'CONSULTATION',
  DIAGNOSTIC_TEST = 'DIAGNOSTIC_TEST',
  PROCEDURE = 'PROCEDURE',
  HOSPITALIZATION = 'HOSPITALIZATION',
  SURGERY = 'SURGERY',
  COUNSELING = 'COUNSELING',
  THERAPY = 'THERAPY',
  NUTRITION = 'NUTRITION',
  MEDICATION_REVIEW = 'MEDICATION_REVIEW',
  IMMUNIZATION = 'IMMUNIZATION',
  LAB_RESULT = 'LAB_RESULT',
  RADIOLOGY = 'RADIOLOGY',
  OTHER = 'OTHER',
}

/**
 * Allergy Severity Levels
 * Clinical allergy severity levels aligned with medical standards
 */
export enum AllergySeverity {
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  SEVERE = 'SEVERE',
  LIFE_THREATENING = 'LIFE_THREATENING',
}

/**
 * User Roles
 * Healthcare user roles for access control
 */
export enum UserRole {
  ADMIN = 'ADMIN',
  NURSE = 'NURSE',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  DISTRICT_ADMIN = 'DISTRICT_ADMIN',
  COUNSELOR = 'COUNSELOR',
  VIEWER = 'VIEWER',
}
