/**
 * Repository Interfaces Index
 * Auto-generated exports
 */

export * from './IRepository';
export * from './IGrowthMeasurementRepository';
export * from './IScreeningRepository';
export * from './IVaccinationRepository';
export * from './IVitalSignsRepository';
export * from './IMedicationInventoryRepository';
export * from './IMedicationLogRepository';
export * from './IStudentMedicationRepository';
export * from './IInventoryItemRepository';
export * from './IInventoryTransactionRepository';
export * from './IPurchaseOrderRepository';
export * from './IPurchaseOrderItemRepository';
export * from './IVendorRepository';
export * from './IIpRestrictionRepository';
export * from './ILoginAttemptRepository';
export * from './IPermissionRepository';
export * from './IRoleRepository';
export * from './IRolePermissionRepository';
export * from './ISecurityIncidentRepository';
export * from './ISessionRepository';
export * from './IUserRoleAssignmentRepository';
export * from './IComplianceChecklistItemRepository';
export * from './IComplianceReportRepository';
export * from './IConsentFormRepository';
export * from './IConsentSignatureRepository';
export * from './IPolicyAcknowledgmentRepository';
export * from './IPolicyDocumentRepository';
export * from './IMessageRepository';
export * from './IMessageDeliveryRepository';
export * from './IMessageTemplateRepository';
export * from './IDocumentRepository';
export * from './IDocumentAuditTrailRepository';
export * from './IDocumentSignatureRepository';
export * from './IFollowUpActionRepository';
export * from './IIncidentReportRepository';
export * from './IWitnessStatementRepository';
export * from './IIntegrationConfigRepository';
export * from './IIntegrationLogRepository';
export * from './IBackupLogRepository';
export * from './IConfigurationHistoryRepository';
export * from './ILicenseRepository';
export * from './IMaintenanceLogRepository';
export * from './IPerformanceMetricRepository';
export * from './ISystemConfigurationRepository';
export * from './ITrainingCompletionRepository';
export * from './ITrainingModuleRepository';
export * from './IAppointmentReminderRepository';
export * from './IAppointmentWaitlistRepository';
export * from './IContactRepository';
export * from './IEmergencyContactRepository';
export * from './INurseAvailabilityRepository';
export * from './IBudgetCategoryRepository';
export * from './IBudgetTransactionRepository';
