/**
 * Compliance Module Enums
 * Centralized export for all compliance-related enumerations
 */

// Compliance Report Enums
export enum ComplianceReportType {
  HIPAA = 'HIPAA',
  FERPA = 'FERPA',
  MEDICATION_AUDIT = 'MEDICATION_AUDIT',
  STATE_HEALTH = 'STATE_HEALTH',
  SAFETY_INSPECTION = 'SAFETY_INSPECTION',
  TRAINING_COMPLIANCE = 'TRAINING_COMPLIANCE',
  DATA_PRIVACY = 'DATA_PRIVACY',
  CUSTOM = 'CUSTOM',
}

export enum ComplianceStatus {
  PENDING = 'PENDING',
  COMPLIANT = 'COMPLIANT',
  NON_COMPLIANT = 'NON_COMPLIANT',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum ComplianceCategory {
  PRIVACY = 'PRIVACY',
  SECURITY = 'SECURITY',
  DOCUMENTATION = 'DOCUMENTATION',
  TRAINING = 'TRAINING',
  MEDICATION = 'MEDICATION',
  HEALTH_RECORDS = 'HEALTH_RECORDS',
  SAFETY = 'SAFETY',
  CONSENT = 'CONSENT',
}

// Checklist Enums
export enum ChecklistItemStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  IN_PROGRESS = 'IN_PROGRESS',
  FAILED = 'FAILED',
}

// Consent Enums
export enum ConsentType {
  MEDICATION_ADMINISTRATION = 'MEDICATION_ADMINISTRATION',
  PHOTO_RELEASE = 'PHOTO_RELEASE',
  FIELD_TRIP = 'FIELD_TRIP',
  EMERGENCY_TREATMENT = 'EMERGENCY_TREATMENT',
  DATA_SHARING = 'DATA_SHARING',
  RESEARCH = 'RESEARCH',
}

// Policy Enums
export enum PolicyCategory {
  HIPAA_PRIVACY = 'HIPAA_PRIVACY',
  HIPAA_SECURITY = 'HIPAA_SECURITY',
  MEDICATION_ADMINISTRATION = 'MEDICATION_ADMINISTRATION',
  EMERGENCY_PROCEDURES = 'EMERGENCY_PROCEDURES',
  CONFIDENTIALITY = 'CONFIDENTIALITY',
  DATA_RETENTION = 'DATA_RETENTION',
  ACCESS_CONTROL = 'ACCESS_CONTROL',
}

export enum PolicyStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  ARCHIVED = 'ARCHIVED',
  SUPERSEDED = 'SUPERSEDED',
}

// Audit Enums
export enum AuditAction {
  CREATE = 'CREATE',
  VIEW = 'VIEW',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  EXPORT = 'EXPORT',
  PRINT = 'PRINT',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
}

// PHI Disclosure Enums
export enum DisclosureType {
  TREATMENT = 'TREATMENT',
  PAYMENT = 'PAYMENT',
  HEALTHCARE_OPERATIONS = 'HEALTHCARE_OPERATIONS',
  AUTHORIZATION = 'AUTHORIZATION',
  REQUIRED_BY_LAW = 'REQUIRED_BY_LAW',
  PUBLIC_HEALTH = 'PUBLIC_HEALTH',
  RESEARCH = 'RESEARCH',
}

export enum DisclosurePurpose {
  TREATMENT = 'TREATMENT',
  PAYMENT = 'PAYMENT',
  OPERATIONS = 'OPERATIONS',
  LEGAL_REQUIREMENT = 'LEGAL_REQUIREMENT',
  PUBLIC_HEALTH = 'PUBLIC_HEALTH',
  RESEARCH = 'RESEARCH',
  PATIENT_REQUEST = 'PATIENT_REQUEST',
}

export enum DisclosureMethod {
  VERBAL = 'VERBAL',
  WRITTEN = 'WRITTEN',
  ELECTRONIC = 'ELECTRONIC',
  FAX = 'FAX',
  PHONE = 'PHONE',
}

export enum RecipientType {
  HEALTHCARE_PROVIDER = 'HEALTHCARE_PROVIDER',
  INSURANCE = 'INSURANCE',
  PARENT_GUARDIAN = 'PARENT_GUARDIAN',
  SCHOOL_OFFICIAL = 'SCHOOL_OFFICIAL',
  GOVERNMENT_AGENCY = 'GOVERNMENT_AGENCY',
  RESEARCHER = 'RESEARCHER',
  OTHER = 'OTHER',
}
