/**
 * @fileoverview HIPAA-Compliant Audit Logging System - Event Type Definitions
 *
 * This module provides core interface definitions for audit events, change tracking,
 * and event creation parameters used throughout the HIPAA-compliant audit logging system.
 *
 * @module AuditEvents
 * @version 1.0.0
 * @since 2025-10-21
 *
 * @description
 * The audit event interfaces define:
 * - **Audit Events**: Complete audit event structure for HIPAA compliance
 * - **Change Tracking**: Field-level change tracking for PHI modifications
 * - **Event Parameters**: Simplified API for creating audit log entries
 *
 * These types enable comprehensive audit trail creation following the "5 W's and H" framework:
 * WHO, WHAT, WHEN, WHERE, WHY, and HOW.
 *
 * @example Basic Audit Event
 * ```typescript
 * import { AuditEvent, AuditAction, AuditResourceType, AuditStatus, AuditSeverity } from './types';
 *
 * const event: AuditEvent = {
 *   userId: 'user123',
 *   action: AuditAction.VIEW_HEALTH_RECORD,
 *   resourceType: AuditResourceType.HEALTH_RECORD,
 *   resourceId: 'record456',
 *   timestamp: new Date().toISOString(),
 *   status: AuditStatus.SUCCESS,
 *   isPHI: true,
 *   isHIPAACompliant: true,
 *   severity: AuditSeverity.MEDIUM
 * };
 * ```
 *
 * @example Change Tracking
 * ```typescript
 * const changes: AuditChange[] = [
 *   {
 *     field: 'allergies',
 *     oldValue: ['Peanuts'],
 *     newValue: ['Peanuts', 'Shellfish'],
 *     type: 'UPDATE'
 *   }
 * ];
 * ```
 *
 * @author Healthcare Development Team
 * @copyright 2025 White Cross Health Systems
 * @license Proprietary - Internal Use Only
 *
 * @requires TypeScript 4.5+
 * @requires HIPAA Compliance Review
 *
 * @see {@link https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html|HIPAA Security Rule}
 * @see {@link https://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html|HIPAA Privacy Rule}
 */

import { AuditAction, AuditResourceType, AuditSeverity, AuditStatus } from './action-types';

// ==========================================
// CORE AUDIT INTERFACES
// ==========================================

/**
 * @interface AuditEvent
 * @description Complete audit event structure capturing comprehensive information
 * for HIPAA compliance. This is the core data structure that represents a single
 * auditable operation in the healthcare system.
 *
 * The audit event follows the "5 W's and H" framework:
 * - **WHO**: User identification and role information
 * - **WHAT**: Action performed and resource affected
 * - **WHEN**: Precise timestamps for compliance tracking
 * - **WHERE**: Device, location, and network context
 * - **WHY**: Business reason and contextual information
 * - **HOW**: Technical method and implementation details
 *
 * **Key Features:**
 * - Tamper-evident checksums for data integrity
 * - Complete change tracking for PHI modifications
 * - Hierarchical severity classification
 * - Local caching for offline resilience
 * - Extensible metadata for custom requirements
 *
 * @example Complete Audit Event
 * ```typescript
 * const event: AuditEvent = {
 *   id: 'audit_1698765432_abc123',
 *   sessionId: 'session_1698765000_xyz789',
 *   userId: 'nurse_456',
 *   userEmail: 'jane.doe@school.edu',
 *   userName: 'Jane Doe',
 *   userRole: 'School Nurse',
 *   action: AuditAction.UPDATE_ALLERGY,
 *   resourceType: AuditResourceType.ALLERGY,
 *   resourceId: 'allergy_789',
 *   resourceIdentifier: 'Peanut Allergy - John Smith',
 *   timestamp: '2025-10-21T14:30:32.123Z',
 *   ipAddress: '10.1.2.3',
 *   userAgent: 'Mozilla/5.0...',
 *   method: 'UI',
 *   status: AuditStatus.SUCCESS,
 *   changes: [{
 *     field: 'severity',
 *     oldValue: 'moderate',
 *     newValue: 'severe',
 *     type: 'UPDATE'
 *   }],
 *   isPHI: true,
 *   isHIPAACompliant: true,
 *   severity: AuditSeverity.HIGH,
 *   studentId: 'student_123',
 *   checksum: 'abc123def456',
 *   localTimestamp: 1698765432123,
 *   isSynced: false
 * };
 * ```
 *
 * @example Minimal Event
 * ```typescript
 * const minimalEvent: AuditEvent = {
 *   userId: 'user_123',
 *   action: AuditAction.VIEW_STUDENT,
 *   resourceType: AuditResourceType.STUDENT,
 *   timestamp: new Date().toISOString(),
 *   status: AuditStatus.SUCCESS,
 *   isPHI: true,
 *   isHIPAACompliant: true,
 *   severity: AuditSeverity.LOW
 * };
 * ```
 *
 * @since 1.0.0
 * @see {@link AuditLogParams} for simplified event creation
 * @see {@link AuditChange} for change tracking details
 */
export interface AuditEvent {
  // Event Identity
  id?: string; // Generated by backend or client
  sessionId?: string; // User session identifier

  // WHO - User Information
  userId: string;
  userEmail?: string;
  userName?: string;
  userRole?: string;

  // WHAT - Action Information
  action: AuditAction;
  resourceType: AuditResourceType;
  resourceId?: string;
  resourceIdentifier?: string; // Human-readable identifier (e.g., student name)

  // WHEN - Temporal Information
  timestamp: string; // ISO 8601 format

  // WHERE - Context Information
  ipAddress?: string;
  userAgent?: string;
  location?: string;
  deviceId?: string;

  // WHY - Reason and Context
  reason?: string;
  context?: Record<string, unknown>;

  // HOW - Method and Details
  method?: 'API' | 'UI' | 'BATCH' | 'SYSTEM';
  endpoint?: string;

  // STATUS - Operation Result
  status: AuditStatus;
  statusCode?: number;
  errorMessage?: string;

  // CHANGE TRACKING - Before/After for Updates
  changes?: AuditChange[];
  beforeState?: Record<string, unknown>;
  afterState?: Record<string, unknown>;

  // PHI AND COMPLIANCE FLAGS
  isPHI: boolean; // Is this Protected Health Information?
  isHIPAACompliant: boolean; // Was action HIPAA-compliant?
  requiresReview?: boolean; // Does this require manual review?

  // SECURITY - Tamper Evidence
  checksum?: string; // Hash of event data for tamper detection
  signature?: string; // Digital signature if available

  // METADATA
  metadata?: Record<string, unknown>;
  tags?: string[];
  severity: AuditSeverity;

  // RELATED ENTITIES
  studentId?: string; // For student-related operations
  schoolId?: string;
  districtId?: string;

  // LOCAL TRACKING
  localTimestamp?: number; // Local timestamp for ordering
  retryCount?: number; // Number of send attempts
  lastRetryAt?: number; // Last retry timestamp
  isSynced?: boolean; // Whether synced to backend
}

/**
 * @interface AuditChange
 * @description Represents a single field change in an audit event, enabling
 * precise tracking of PHI modifications for compliance and accountability.
 *
 * Change tracking is essential for HIPAA compliance as it provides:
 * - Detailed modification history
 * - Before/after values for rollback capability
 * - Change type classification for reporting
 * - Field-level granularity for sensitive data
 *
 * @example Basic Change Tracking
 * ```typescript
 * const changes: AuditChange[] = [
 *   {
 *     field: 'email',
 *     oldValue: 'old@example.com',
 *     newValue: 'new@example.com',
 *     type: 'UPDATE'
 *   },
 *   {
 *     field: 'phoneNumbers',
 *     oldValue: null,
 *     newValue: ['+1-555-0123'],
 *     type: 'ADD'
 *   },
 *   {
 *     field: 'tempAddress',
 *     oldValue: '123 Old St',
 *     newValue: null,
 *     type: 'REMOVE'
 *   }
 * ];
 * ```
 *
 * @example Nested Object Changes
 * ```typescript
 * const nestedChange: AuditChange = {
 *   field: 'vitals.bloodPressure.systolic',
 *   oldValue: 120,
 *   newValue: 118,
 *   type: 'UPDATE'
 * };
 * ```
 *
 * @since 1.0.0
 * @see {@link AuditEvent.changes} for usage in audit events
 */
export interface AuditChange {
  field: string;
  oldValue: unknown;
  newValue: unknown;
  type?: 'ADD' | 'UPDATE' | 'REMOVE';
}

/**
 * @interface AuditLogParams
 * @description Simplified parameters for creating audit log entries. This interface
 * provides a developer-friendly API for logging operations without requiring
 * knowledge of the complete AuditEvent structure.
 *
 * The service automatically enhances these parameters with:
 * - User context from authentication state
 * - System-generated timestamps and IDs
 * - Security checksums and signatures
 * - Default severity levels based on action type
 * - PHI classification based on resource type
 *
 * **Parameter Categories:**
 * - **Required**: action, resourceType
 * - **Identification**: resourceId, resourceIdentifier, studentId
 * - **Status**: status (defaults to SUCCESS)
 * - **Change Tracking**: changes, beforeState, afterState
 * - **Context**: reason, context, metadata, tags
 * - **Classification**: isPHI, severity
 *
 * @example Basic Logging
 * ```typescript
 * await auditService.log({
 *   action: AuditAction.VIEW_HEALTH_RECORD,
 *   resourceType: AuditResourceType.HEALTH_RECORD,
 *   resourceId: 'health_record_456',
 *   studentId: 'student_123'
 * });
 * ```
 *
 * @example Detailed Change Logging
 * ```typescript
 * await auditService.log({
 *   action: AuditAction.UPDATE_MEDICATION,
 *   resourceType: AuditResourceType.MEDICATION,
 *   resourceId: 'med_789',
 *   resourceIdentifier: 'Albuterol Inhaler - Jane Doe',
 *   studentId: 'student_456',
 *   status: AuditStatus.SUCCESS,
 *   changes: [{
 *     field: 'dosage',
 *     oldValue: '2 puffs',
 *     newValue: '1 puff',
 *     type: 'UPDATE'
 *   }],
 *   reason: 'Dosage adjustment per physician orders',
 *   severity: AuditSeverity.HIGH,
 *   metadata: {
 *     physicianId: 'doc_123',
 *     orderDate: '2025-10-21'
 *   }
 * });
 * ```
 *
 * @example Error Logging
 * ```typescript
 * await auditService.log({
 *   action: AuditAction.DELETE_ALLERGY,
 *   resourceType: AuditResourceType.ALLERGY,
 *   resourceId: 'allergy_999',
 *   status: AuditStatus.FAILURE,
 *   reason: 'Insufficient permissions',
 *   context: {
 *     requiredRole: 'admin',
 *     userRole: 'viewer'
 *   }
 * });
 * ```
 *
 * @since 1.0.0
 * @see {@link AuditService.log} for usage
 * @see {@link AuditEvent} for complete event structure
 */
export interface AuditLogParams {
  action: AuditAction;
  resourceType: AuditResourceType;
  resourceId?: string;
  resourceIdentifier?: string;
  studentId?: string;
  status?: AuditStatus;
  isPHI?: boolean;
  changes?: AuditChange[];
  beforeState?: Record<string, unknown>;
  afterState?: Record<string, unknown>;
  reason?: string;
  context?: Record<string, unknown>;
  severity?: AuditSeverity;
  metadata?: Record<string, unknown>;
  tags?: string[];
}
