import type { Medication } from './core.types';
import type { MedicationAdministration } from './administration.types';

/**
 * Mock medication data for development and testing
 *
 * @description Example medications demonstrating various types and scenarios
 */
export const mockMedications: Medication[] = [
  {
    id: '1',
    name: 'Albuterol Inhaler',
    genericName: 'Albuterol Sulfate',
    brandName: 'ProAir HFA',
    ndc: '49502-497-17',
    type: 'inhaler',
    status: 'active',
    strength: '90 mcg',
    dosageForm: 'Metered Dose Inhaler',
    administrationRoute: 'inhaled',
    frequency: 'as_needed',
    dosageInstructions: '2 puffs as needed for asthma symptoms, not to exceed 8 puffs per day',
    maxDailyDose: 8,
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-09-01'),
    studentId: 'student-1',
    createdBy: 'nurse-1',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
    isControlled: false,
    requiresParentConsent: true,
    requiresPhysicianOrder: true,
    specialInstructions: 'Shake well before use. Rinse mouth after administration.',
    warnings: ['May cause nervousness, shakiness, or fast heartbeat'],
  },
  {
    id: '2',
    name: 'EpiPen Jr',
    genericName: 'Epinephrine',
    brandName: 'EpiPen Jr',
    type: 'epipen',
    status: 'active',
    strength: '0.15 mg',
    dosageForm: 'Auto-Injector',
    administrationRoute: 'injection',
    frequency: 'as_needed',
    dosageInstructions: 'Inject into outer thigh for severe allergic reactions. Call 911 immediately.',
    startDate: new Date('2024-08-15'),
    endDate: new Date('2025-08-15'),
    studentId: 'student-2',
    createdBy: 'nurse-2',
    createdAt: new Date('2024-08-15'),
    updatedAt: new Date('2024-08-15'),
    isControlled: false,
    requiresParentConsent: true,
    requiresPhysicianOrder: true,
    specialInstructions: 'Keep at room temperature. Do not refrigerate or freeze.',
    warnings: ['For emergency use only', 'May cause rapid heart rate and anxiety'],
    contraindications: ['No known contraindications in emergency situations'],
  },
  {
    id: '3',
    name: 'Methylphenidate ER',
    genericName: 'Methylphenidate Hydrochloride',
    brandName: 'Concerta',
    ndc: '50458-588-60',
    type: 'controlled_substance',
    status: 'active',
    strength: '18 mg',
    dosageForm: 'Extended-Release Tablet',
    administrationRoute: 'oral',
    frequency: 'once_daily',
    dosageInstructions: 'Take 1 tablet by mouth every morning with or without food',
    maxDailyDose: 1,
    startDate: new Date('2024-09-01'),
    endDate: new Date('2025-09-01'),
    prescriberId: 'doc-123',
    prescriberName: 'Dr. Sarah Johnson',
    prescriptionNumber: 'RX-2024-001234',
    prescribedDate: new Date('2024-08-28'),
    studentId: 'student-3',
    createdBy: 'nurse-1',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
    isControlled: true,
    requiresParentConsent: true,
    requiresPhysicianOrder: true,
    specialInstructions: 'Must be stored in locked cabinet. Administer in morning only.',
    warnings: [
      'May cause decreased appetite and sleep problems',
      'Monitor for mood changes or unusual behavior',
      'Schedule II controlled substance',
    ],
    contraindications: ['Glaucoma', 'Severe anxiety or agitation', 'MAO inhibitor use within 14 days'],
    sideEffects: ['Decreased appetite', 'Difficulty sleeping', 'Stomach pain', 'Headache'],
    notes: 'Parent prefers administration at 8:00 AM',
  },
  {
    id: '4',
    name: 'Ibuprofen',
    genericName: 'Ibuprofen',
    type: 'over_the_counter',
    status: 'active',
    strength: '200 mg',
    dosageForm: 'Tablet',
    administrationRoute: 'oral',
    frequency: 'as_needed',
    dosageInstructions: '1-2 tablets every 6 hours as needed for pain or fever, not to exceed 6 tablets per day',
    maxDailyDose: 6,
    startDate: new Date('2024-09-01'),
    studentId: 'student-1',
    createdBy: 'nurse-1',
    createdAt: new Date('2024-09-01'),
    updatedAt: new Date('2024-09-01'),
    isControlled: false,
    requiresParentConsent: true,
    requiresPhysicianOrder: false,
    specialInstructions: 'Take with food to minimize stomach upset.',
    warnings: ['May cause stomach upset or bleeding', 'Do not exceed maximum daily dose'],
    contraindications: ['Aspirin allergy', 'Active stomach ulcer', 'Severe kidney disease'],
    sideEffects: ['Stomach upset', 'Heartburn', 'Dizziness', 'Rash'],
  },
];

/**
 * Mock administration records for development and testing
 *
 * @description Example administration logs demonstrating various outcomes
 */
export const mockMedicationAdministrations: MedicationAdministration[] = [
  {
    id: '1',
    medicationId: '1',
    studentId: 'student-1',
    administeredBy: 'nurse-1',
    administeredDate: new Date('2024-10-31T10:30:00'),
    dosageGiven: '2 puffs',
    administrationRoute: 'inhaled',
    administrationStatus: 'completed',
    parentNotified: true,
    notes: 'Student reported difficulty breathing during PE class',
    createdAt: new Date('2024-10-31T10:30:00'),
    updatedAt: new Date('2024-10-31T10:30:00'),
  },
  {
    id: '2',
    medicationId: '3',
    studentId: 'student-3',
    administeredBy: 'nurse-1',
    administeredDate: new Date('2024-11-04T08:00:00'),
    dosageGiven: '1 tablet (18mg)',
    administrationRoute: 'oral',
    administrationStatus: 'completed',
    witnessedBy: 'admin-1',
    parentNotified: false,
    notes: 'Routine morning dose. Student took medication without issue.',
    createdAt: new Date('2024-11-04T08:00:00'),
    updatedAt: new Date('2024-11-04T08:00:00'),
  },
  {
    id: '3',
    medicationId: '4',
    studentId: 'student-1',
    administeredBy: 'nurse-2',
    administeredDate: new Date('2024-11-04T11:15:00'),
    dosageGiven: '2 tablets (400mg)',
    administrationRoute: 'oral',
    administrationStatus: 'completed',
    parentNotified: true,
    notes: 'Student complained of headache after lunch.',
    createdAt: new Date('2024-11-04T11:15:00'),
    updatedAt: new Date('2024-11-04T11:15:00'),
  },
  {
    id: '4',
    medicationId: '3',
    studentId: 'student-3',
    administeredBy: 'nurse-1',
    administeredDate: new Date('2024-11-03T08:00:00'),
    dosageGiven: '1 tablet (18mg)',
    administrationRoute: 'oral',
    administrationStatus: 'refused',
    refusalReason: 'Student stated medication makes them feel "weird"',
    witnessedBy: 'admin-1',
    parentNotified: true,
    notes: 'Parent notified. Will follow up with prescriber.',
    createdAt: new Date('2024-11-03T08:00:00'),
    updatedAt: new Date('2024-11-03T08:00:00'),
  },
];
