/**
 * Report Type
 */
export enum ReportType {
  IMMUNIZATION_COMPLIANCE = 'IMMUNIZATION_COMPLIANCE',
  MEDICATION_ADMINISTRATION = 'MEDICATION_ADMINISTRATION',
  CONTROLLED_SUBSTANCE = 'CONTROLLED_SUBSTANCE',
  INCIDENT_SUMMARY = 'INCIDENT_SUMMARY',
  HEALTH_SCREENINGS = 'HEALTH_SCREENINGS',
  HIPAA_AUDIT = 'HIPAA_AUDIT',
  DATA_ACCESS_LOG = 'DATA_ACCESS_LOG',
  STUDENT_HEALTH_SUMMARY = 'STUDENT_HEALTH_SUMMARY',
  EMERGENCY_PREPAREDNESS = 'EMERGENCY_PREPAREDNESS',
  NURSING_VISIT_LOG = 'NURSING_VISIT_LOG',
  CHRONIC_CONDITION_MANAGEMENT = 'CHRONIC_CONDITION_MANAGEMENT',
  STATE_MANDATED = 'STATE_MANDATED',
}
