/**
 * @fileoverview Mock Vendor Data
 * @module app/(dashboard)/vendors/_components/vendors.mock
 *
 * Mock vendor data for demonstration and development purposes.
 */

import type { Vendor } from './vendors.types'

/**
 * Mock vendor data for demonstration
 */
export const mockVendors: Vendor[] = [
  {
    id: 'vendor-1',
    name: 'Medical Supplies Inc.',
    legalName: 'Medical Supplies Incorporated',
    vendorNumber: 'V-001',
    status: 'ACTIVE',
    rating: 'EXCELLENT',
    contacts: [
      {
        id: 'c1',
        name: 'John Smith',
        title: 'Account Manager',
        email: 'john.smith@medisupply.com',
        phone: '(555) 123-4567',
        isPrimary: true,
      },
    ],
    addresses: [
      {
        id: 'a1',
        type: 'BOTH',
        street1: '123 Medical Way',
        city: 'Healthcare City',
        state: 'CA',
        zipCode: '90210',
        country: 'US',
        isPrimary: true,
      },
    ],
    website: 'https://medisupply.com',
    taxId: '12-3456789',
    paymentTerms: 'Net 30',
    preferredPaymentMethod: 'ACH',
    creditLimit: 150000,
    categories: ['Medical Supplies', 'Equipment'],
    productLines: ['Bandages', 'Syringes', 'Medical Equipment'],
    certifications: [
      {
        id: 'cert-1',
        name: 'FDA Registration',
        type: 'Regulatory',
        issuedBy: 'FDA',
        issuedDate: '2024-01-01',
        expiryDate: '2025-12-31',
        status: 'VALID',
      },
    ],
    performance: {
      vendorId: 'vendor-1',
      overallRating: 'EXCELLENT',
      ratingScore: 95,
      onTimeDeliveryRate: 96,
      averageDeliveryDays: 5,
      lateDeliveries: 2,
      earlyDeliveries: 18,
      defectRate: 0.5,
      returnRate: 0.3,
      qualityScore: 98,
      totalOrders: 45,
      completedOrders: 43,
      cancelledOrders: 2,
      totalValue: 125000,
      averageOrderValue: 2777,
      complianceRate: 98,
      documentationScore: 96,
      averageResponseTime: 4,
      communicationScore: 93,
      priceCompetitiveness: 88,
      totalSpend: 125000,
      costSavings: 5000,
      periodStart: '2024-07-01',
      periodEnd: '2025-06-30',
      lastUpdated: '2025-01-26',
    },
    w9OnFile: true,
    insuranceCertOnFile: true,
    contractOnFile: true,
    backgroundCheckCompleted: true,
    createdBy: 'user1',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2025-01-15T00:00:00Z',
    lastModifiedBy: 'user1',
    lastOrderDate: '2025-01-15',
  },
  {
    id: 'vendor-2',
    name: 'Pharma Distributors LLC',
    legalName: 'Pharma Distributors Limited Liability Company',
    vendorNumber: 'V-002',
    status: 'ACTIVE',
    rating: 'GOOD',
    contacts: [
      {
        id: 'c2',
        name: 'Sarah Johnson',
        title: 'Account Manager',
        email: 'sarah.johnson@pharmadist.com',
        phone: '(555) 987-6543',
        isPrimary: true,
      },
    ],
    addresses: [
      {
        id: 'a2',
        type: 'BILLING',
        street1: '456 Pharma Blvd',
        city: 'Los Angeles',
        state: 'CA',
        zipCode: '90001',
        country: 'US',
        isPrimary: true,
      },
    ],
    website: 'https://pharmadist.com',
    taxId: '98-7654321',
    paymentTerms: 'Net 45',
    preferredPaymentMethod: 'Check',
    creditLimit: 100000,
    categories: ['Medications', 'Prescriptions'],
    productLines: ['EpiPens', 'Inhalers', 'Medications'],
    certifications: [
      {
        id: 'cert-2',
        name: 'DEA License',
        type: 'Controlled Substances',
        issuedBy: 'DEA',
        issuedDate: '2024-03-01',
        expiryDate: '2026-02-28',
        status: 'VALID',
      },
    ],
    performance: {
      vendorId: 'vendor-2',
      overallRating: 'GOOD',
      ratingScore: 82,
      onTimeDeliveryRate: 87,
      averageDeliveryDays: 12,
      lateDeliveries: 8,
      earlyDeliveries: 12,
      defectRate: 2.1,
      returnRate: 1.2,
      qualityScore: 85,
      totalOrders: 32,
      completedOrders: 30,
      cancelledOrders: 2,
      totalValue: 280000,
      averageOrderValue: 8750,
      complianceRate: 94,
      documentationScore: 90,
      averageResponseTime: 6,
      communicationScore: 88,
      priceCompetitiveness: 92,
      totalSpend: 280000,
      costSavings: 12000,
      periodStart: '2024-07-01',
      periodEnd: '2025-06-30',
      lastUpdated: '2025-01-26',
    },
    w9OnFile: true,
    insuranceCertOnFile: true,
    contractOnFile: true,
    backgroundCheckCompleted: true,
    createdBy: 'user1',
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2025-01-10T00:00:00Z',
    lastModifiedBy: 'user1',
    lastOrderDate: '2025-01-10',
  },
  {
    id: 'vendor-3',
    name: 'First Aid Solutions Corp',
    legalName: 'First Aid Solutions Corporation',
    vendorNumber: 'V-003',
    status: 'ACTIVE',
    rating: 'AVERAGE',
    contacts: [
      {
        id: 'c3',
        name: 'Mike Wilson',
        title: 'Sales Representative',
        email: 'mike.wilson@firstaid.com',
        phone: '(555) 456-7890',
        isPrimary: true,
      },
    ],
    addresses: [
      {
        id: 'a3',
        type: 'SHIPPING',
        street1: '789 Emergency Lane',
        city: 'Safety Town',
        state: 'TX',
        zipCode: '75001',
        country: 'US',
        isPrimary: true,
      },
    ],
    website: 'https://firstaid.com',
    taxId: '45-6789012',
    paymentTerms: 'Net 15',
    preferredPaymentMethod: 'Credit Card',
    creditLimit: 75000,
    categories: ['First Aid', 'Emergency Supplies'],
    productLines: ['First Aid Kits', 'AED Units', 'Emergency Medications'],
    certifications: [],
    performance: {
      vendorId: 'vendor-3',
      overallRating: 'AVERAGE',
      ratingScore: 75,
      onTimeDeliveryRate: 78,
      averageDeliveryDays: 8,
      lateDeliveries: 15,
      earlyDeliveries: 5,
      defectRate: 3.2,
      returnRate: 2.1,
      qualityScore: 80,
      totalOrders: 28,
      completedOrders: 25,
      cancelledOrders: 3,
      totalValue: 85000,
      averageOrderValue: 3035,
      complianceRate: 88,
      documentationScore: 82,
      averageResponseTime: 8,
      communicationScore: 76,
      priceCompetitiveness: 85,
      totalSpend: 85000,
      costSavings: 2500,
      periodStart: '2024-07-01',
      periodEnd: '2025-06-30',
      lastUpdated: '2025-01-20',
    },
    w9OnFile: true,
    insuranceCertOnFile: false,
    contractOnFile: true,
    backgroundCheckCompleted: true,
    createdBy: 'user2',
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2025-01-20T00:00:00Z',
    lastModifiedBy: 'user2',
    lastOrderDate: '2025-01-05',
  },
]
